# Generated by Django 5.1.4 on 2025-09-23 08:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Jockey",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="レコードが作成された日時",
                        verbose_name="作成日時",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="レコードが最後に更新された日時",
                        verbose_name="更新日時",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="騎手名")),
                (
                    "birth_date",
                    models.DateField(blank=True, null=True, verbose_name="生年月日"),
                ),
                (
                    "debut_date",
                    models.DateField(blank=True, null=True, verbose_name="デビュー日"),
                ),
                (
                    "stable",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="所属厩舎"
                    ),
                ),
                (
                    "license_type",
                    models.CharField(
                        choices=[
                            ("flat", "平地"),
                            ("jump", "障害"),
                            ("both", "平地・障害"),
                        ],
                        default="flat",
                        max_length=20,
                        verbose_name="免許種別",
                    ),
                ),
                (
                    "total_races",
                    models.IntegerField(default=0, verbose_name="総騎乗数"),
                ),
                ("total_wins", models.IntegerField(default=0, verbose_name="勝利数")),
                ("win_rate", models.FloatField(default=0.0, verbose_name="勝率")),
            ],
            options={
                "verbose_name": "騎手",
                "verbose_name_plural": "騎手",
            },
        ),
        migrations.CreateModel(
            name="Horse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="レコードが作成された日時",
                        verbose_name="作成日時",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="レコードが最後に更新された日時",
                        verbose_name="更新日時",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="馬名")),
                ("birth_date", models.DateField(verbose_name="生年月日")),
                (
                    "sex",
                    models.CharField(
                        choices=[("male", "牡"), ("female", "牝"), ("gelding", "セン")],
                        max_length=10,
                        verbose_name="性別",
                    ),
                ),
                (
                    "owner",
                    models.CharField(blank=True, max_length=255, verbose_name="馬主"),
                ),
                (
                    "trainer",
                    models.CharField(blank=True, max_length=255, verbose_name="調教師"),
                ),
                (
                    "breeder",
                    models.CharField(blank=True, max_length=255, verbose_name="生産者"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="このレコードを作成したユーザー",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="作成者",
                    ),
                ),
                (
                    "dam",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="offspring_as_dam",
                        to="horses.horse",
                        verbose_name="母",
                    ),
                ),
                (
                    "sire",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="offspring_as_sire",
                        to="horses.horse",
                        verbose_name="父",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="このレコードを最後に更新したユーザー",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="更新者",
                    ),
                ),
            ],
            options={
                "verbose_name": "馬",
                "verbose_name_plural": "馬",
            },
        ),
        migrations.CreateModel(
            name="HorsePerformance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="レコードが作成された日時",
                        verbose_name="作成日時",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="レコードが最後に更新された日時",
                        verbose_name="更新日時",
                    ),
                ),
                ("finish_position", models.IntegerField(verbose_name="着順")),
                (
                    "finish_time",
                    models.CharField(blank=True, max_length=20, verbose_name="タイム"),
                ),
                ("weight", models.FloatField(verbose_name="斤量")),
                (
                    "horse_weight",
                    models.IntegerField(blank=True, null=True, verbose_name="馬体重"),
                ),
                ("distance", models.IntegerField(verbose_name="距離")),
                (
                    "track_condition",
                    models.CharField(max_length=20, verbose_name="馬場状態"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="このレコードを作成したユーザー",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="作成者",
                    ),
                ),
                (
                    "horse",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="performances",
                        to="horses.horse",
                    ),
                ),
            ],
            options={
                "verbose_name": "馬成績",
                "verbose_name_plural": "馬成績",
            },
        ),
    ]
