# Generated by Django 5.1.4 on 2025-09-23 08:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("horses", "0001_initial"),
        ("races", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="horseperformance",
            name="race",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="races.race"
            ),
        ),
        migrations.AddField(
            model_name="horseperformance",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                help_text="このレコードを最後に更新したユーザー",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_updated",
                to=settings.AUTH_USER_MODEL,
                verbose_name="更新者",
            ),
        ),
        migrations.AddField(
            model_name="jockey",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                help_text="このレコードを作成したユーザー",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_created",
                to=settings.AUTH_USER_MODEL,
                verbose_name="作成者",
            ),
        ),
        migrations.AddField(
            model_name="jockey",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                help_text="このレコードを最後に更新したユーザー",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_updated",
                to=settings.AUTH_USER_MODEL,
                verbose_name="更新者",
            ),
        ),
        migrations.AddField(
            model_name="horseperformance",
            name="jockey",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="horses.jockey"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="horseperformance",
            unique_together={("horse", "race")},
        ),
    ]
