"""
Django settings for app_config project.

Generated by 'django-admin startproject' using Django 5.1.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
import os
from datetime import datetime

# ベースフォルダ設定
BASE_DIR = Path(__file__).resolve().parent.parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-t3m62y#=l@y&-rq21_q3q1dl#4ux2h4w5&-wcwwwkzermv5fve'

ALLOWED_HOSTS = ['127.0.0.1', 'localhost']
DEBUG = True

# インストールアプリケーション
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'app_folder.apps.AppFolderConfig',
    'bootstrap4',
    'import_export',
    'celery_progress',
    'django_extensions',
    # 'channels',
]

# 使用ミドルウェア
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'app_config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'app_config.wsgi.application'

# Database configuration
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'd_db', 
        'USER': 'postgres',
        'PASSWORD': 'hojo4533',
        'HOST': 'localhost',
        'PORT': '5432',
    }
}

# Celeryの設定
CELERY_BROKER_URL = 'redis://localhost:6379/0'  # Redisをブローカーとして使用
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_BACKEND = 'redis://localhost:6379/0'  # 結果バックエンドとしてRedisを使用
CELERY_BROKER_CONNECTION_RETRY_ON_STARTUP = True
# Logs directory creation (if it does not exist)
LOGS_DIR = os.path.join(BASE_DIR, 'logs')
if not os.path.exists(LOGS_DIR):
    os.makedirs(LOGS_DIR)

# ログ設定
current_date = datetime.now().strftime('%Y-%m-%d')
LOG_FILE_PATH = os.path.join(LOGS_DIR, f'app_logs_{current_date}.log')
ERROR_LOG_FILE_PATH = os.path.join(LOGS_DIR, f'app_errors_{current_date}.log')
WARNING_LOG_FILE_PATH = os.path.join(LOGS_DIR, f'app_warnings_{current_date}.log')

# Logging configuration
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {message}',
            'style': '{',  # f-string style
        },
        'simple': {
            'format': '{levelname} {message}',
            'style': '{',  # f-string style
        },
    },
    'handlers': {
        # Display warnings and above in console
        'console_warning': {
            'level': 'WARNING',  # Only WARNING and above will be displayed
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
        },
        # Save error logs to file
        'file_error': {
            'level': 'ERROR',  # Only ERROR and above will be saved
            'class': 'logging.FileHandler',
            'filename': ERROR_LOG_FILE_PATH,
            'formatter': 'verbose',
        },
        # Save warnings and above to file
        'file_warning': {
            'level': 'WARNING',  # Only WARNING and above will be saved
            'class': 'logging.FileHandler',
            'filename': WARNING_LOG_FILE_PATH,
            'formatter': 'verbose',
        },
        # Save normal logs to file (only WARNING and above will be saved in this case)
        'file_info': {
            'level': 'WARNING',  # Only WARNING and above will be saved
            'class': 'logging.FileHandler',
            'filename': LOG_FILE_PATH,
            'formatter': 'verbose',
        },
    },
    'loggers': {
        'django': {
            'handlers': ['console_warning', 'file_info', 'file_warning', 'file_error'],
            'level': 'WARNING',  # Only WARNING and above will be logged for django logs
            'propagate': True,
        },
        'django.request': {
            'handlers': ['file_error'],  # Save error logs to file
            'level': 'ERROR',  # Only ERROR and above will be logged for django.request
            'propagate': False,
        },
    },
}

# Password validation
AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator'},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},
]

# Internationalization settings
LANGUAGE_CODE = 'ja'
TIME_ZONE = 'Asia/Tokyo'
USE_I18N = True
USE_TZ = True

# Default primary key field type
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# プロジェクト階層
PROJECT_NAME = os.path.basename(BASE_DIR)

## 静的フォルダ
STATIC_URL = '/static/'
# 開発環境時に配置される
STATICFILES_DIRS = [os.path.join(BASE_DIR, 'static')] 
# 本番環境時にコマンドで上記から一括移動できる。
STATIC_ROOT = '/var/www/{}/static'.format(PROJECT_NAME)

## 画像フォルダ
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Custom user model
AUTH_USER_MODEL = 'app_folder.CustomUser'

# Redirect URLs
LOGIN_REDIRECT_URL = '/app_folder/dashboard/'

# Chromeドライバ関連の設定
MAX_RETRIES = 5

HEADERS = {
    'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36',
    'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8',
    'Accept-Encoding': 'gzip, deflate, br',
    'Accept-Language': 'ja,en;q=0.9',
    'Connection': 'keep-alive',
    'Referer': 'https://www.google.com/',
    'Upgrade-Insecure-Requests': '1',
    'Cache-Control': 'max-age=0',
    'TE': 'Trailers'
}

USER_AGENTS = [
        'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36',
        'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.159 Safari/537.36',
        'Mozilla/5.0 (X11; Ubuntu; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/93.0.4577.82 Safari/537.36',
        'Mozilla/5.0 (Windows NT 6.1; WOW64; rv:40.0) Gecko/20100101 Firefox/40.0',
        'Mozilla/5.0 (Windows NT 6.1; rv:60.0) Gecko/20100101 Firefox/60.0'
    ]

# 列名の設定
BASE_COL = [
    '枠', '馬 番', '馬名', '性齢', '斤量', '騎手', '厩舎', '馬体重 (増減)', 'オッズ', '人気'
]

RESULT_COL = [
    'race_id', '馬 番', '馬名', '着 順', 'タイム', 'コーナー 通過順'
]

HORSE_COL = [
    '日付', '開催', '天 気', 'レース名', '頭 数', '枠 番', '馬 番', 'オ ッ ズ', '人 気', '着 順',
    '騎手', '斤 量', '距離', '馬 場', 'タイム', '着差', '通過', 'ペース', '上り', '馬体重',
    '勝ち馬 (2着馬)', '賞金', 'new_flg', 'win_1_flg', 'win_2_flg', 'win_3_flg', 'not_win_flg',
    'g3_flg', 'g2_flg', 'g1_flg', 'l_flg', 'op_flg'
]

JOCKEY_COL = [
    '日付', '開催', 'R', '天 気', 'レース名', '頭 数', '枠 番', '馬 番', '単勝', '人 気', '着 順',
    '馬名', '斤 量', '距離', '馬 場', 'タイム', '着差', '通過', 'ペース', '上り', '馬体重',
    '勝ち馬', '賞金 (万円)', 'new_flg', 'win_1_flg', 'win_2_flg', 'win_3_flg', 'not_win_flg',
    'g3_flg', 'g2_flg', 'g1_flg', 'l_flg', 'op_flg'
]

HORSE_BLOOD_COL = [
    'sire_1_male', 'sire_1_female', 'sire_2_1_male', 'sire_2_1_female', 
    'sire_2_2_male', 'sire_2_2_female'
]

NEW_BASE_COL = {
    '枠': 'frame_number',
    '馬 番': 'horse_number',
    '馬名': 'horse_name',
    '性齢': 'sex',
    '斤量': 'weight',
    '騎手': 'jockey_name',
    '厩舎': 'stable_name',
    '馬体重 (増減)': 'body_weight',
    'オッズ': 'odds',
    '人気': 'popularity',
    '馬リンク': 'horse_url',
    '騎手リンク': 'jockey_url'
}

NEW_RESULT_COL = {
    'race_id': 'race_id',
    '馬 番': 'horse_number',
    '馬名': 'horse_name',
    '着 順': 'rank',
    'タイム': 'race_time',
    'コーナー 通過順': 'corner_order'
}

NEW_HORSE_COL = {
    '日付': 'race_date', 
    '開催': 'race_place',
    '天 気': 'weather',
    'レース名': 'race_name',
    '頭 数': 'count',
    '枠 番': 'frame',
    '馬 番': 'horse_number',
    'オ ッ ズ': 'odds',
    '人 気': 'popularity',
    '着 順': 'rank',
    '騎手': 'jockey',
    '斤 量': 'weight',
    '距離': 'distance',
    '馬 場': 'track_condition',
    'タイム': 'time',
    '着差': 'time_diff',
    '通過': 'position',
    'ペース': 'pace',
    '上り': 'up',
    '馬体重': 'body_weight',
    '勝ち馬 (2着馬)': 'winner',
    '賞金': 'prize',
}

NEW_JOCKEY_COL = {
    '日付': 'race_date', 
    '開催': 'race_place',
    '天 気': 'weather',
    'R':'race',
    'レース名': 'race_name',
    '頭 数': 'count',
    '枠 番': 'frame',
    '馬 番': 'horse_number',
    '単勝': 'odds',
    '人 気': 'popularity',
    '着 順': 'rank',
    '馬名': 'horse',
    '斤 量': 'weight',
    '距離': 'distance',
    '馬 場': 'track_condition',
    'タイム': 'time',
    '着差': 'time_diff',
    '通過': 'position',
    'ペース': 'pace',
    '上り': 'up',
    '馬体重': 'body_weight',
    '勝ち馬': 'winner',
    '賞金 (万円)': 'prize',
}

URL_HEAD = 'https://race.netkeiba.com/race/shutuba.html?race_id='
ASGI_APPLICATION = "app_folder.asgi.application"