"""
Django settings for app_config project.

Generated by 'django-admin startproject' using Django 5.1.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from .base import * # base.pyを読み込む 

# base.pyにない分を補完

DEBUG = True

ALLOWED_HOSTS = ['']
