# Generated by Django 5.1.4 on 2025-09-23 09:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ScrapingJob",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="レコードが作成された日時",
                        verbose_name="作成日時",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="レコードが最後に更新された日時",
                        verbose_name="更新日時",
                    ),
                ),
                (
                    "job_type",
                    models.CharField(
                        choices=[
                            ("race_data", "レースデータ"),
                            ("horse_data", "馬データ"),
                            ("jockey_data", "騎手データ"),
                            ("odds_data", "オッズデータ"),
                            ("result_data", "結果データ"),
                        ],
                        max_length=20,
                        verbose_name="ジョブタイプ",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "待機中"),
                            ("running", "実行中"),
                            ("completed", "完了"),
                            ("failed", "失敗"),
                            ("cancelled", "キャンセル"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="ステータス",
                    ),
                ),
                ("target_url", models.URLField(blank=True, verbose_name="対象URL")),
                (
                    "target_date",
                    models.DateField(blank=True, null=True, verbose_name="対象日"),
                ),
                (
                    "parameters",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="パラメータ"
                    ),
                ),
                (
                    "result_data",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="結果データ"
                    ),
                ),
                (
                    "error_message",
                    models.TextField(blank=True, verbose_name="エラーメッセージ"),
                ),
                (
                    "started_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="開始時刻"
                    ),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="完了時刻"
                    ),
                ),
                (
                    "retry_count",
                    models.IntegerField(default=0, verbose_name="リトライ回数"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="このレコードを作成したユーザー",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="作成者",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="このレコードを最後に更新したユーザー",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="更新者",
                    ),
                ),
            ],
            options={
                "verbose_name": "スクレイピングジョブ",
                "verbose_name_plural": "スクレイピングジョブ",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ScrapingLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="レコードが作成された日時",
                        verbose_name="作成日時",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="レコードが最後に更新された日時",
                        verbose_name="更新日時",
                    ),
                ),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("debug", "DEBUG"),
                            ("info", "INFO"),
                            ("warning", "WARNING"),
                            ("error", "ERROR"),
                            ("critical", "CRITICAL"),
                        ],
                        max_length=10,
                        verbose_name="ログレベル",
                    ),
                ),
                ("message", models.TextField(verbose_name="メッセージ")),
                ("url", models.URLField(blank=True, verbose_name="URL")),
                (
                    "response_code",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="レスポンスコード"
                    ),
                ),
                (
                    "response_time",
                    models.FloatField(
                        blank=True, null=True, verbose_name="レスポンス時間（秒）"
                    ),
                ),
                (
                    "data_size",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="データサイズ（バイト）"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="このレコードを作成したユーザー",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="作成者",
                    ),
                ),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="logs",
                        to="scraping.scrapingjob",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="このレコードを最後に更新したユーザー",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="更新者",
                    ),
                ),
            ],
            options={
                "verbose_name": "スクレイピングログ",
                "verbose_name_plural": "スクレイピングログ",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ScrapingSource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="レコードが作成された日時",
                        verbose_name="作成日時",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="レコードが最後に更新された日時",
                        verbose_name="更新日時",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="サイト名")),
                ("base_url", models.URLField(verbose_name="ベースURL")),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="アクティブ"),
                ),
                (
                    "delay_seconds",
                    models.FloatField(default=1.0, verbose_name="アクセス間隔（秒）"),
                ),
                (
                    "max_retries",
                    models.IntegerField(default=3, verbose_name="最大リトライ回数"),
                ),
                (
                    "timeout_seconds",
                    models.IntegerField(default=30, verbose_name="タイムアウト（秒）"),
                ),
                ("user_agent", models.TextField(blank=True, verbose_name="User-Agent")),
                (
                    "headers",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="HTTPヘッダー"
                    ),
                ),
                (
                    "cookies",
                    models.JSONField(blank=True, default=dict, verbose_name="Cookie"),
                ),
                (
                    "requests_per_minute",
                    models.IntegerField(
                        default=60, verbose_name="分間リクエスト数制限"
                    ),
                ),
                (
                    "daily_request_limit",
                    models.IntegerField(
                        default=10000, verbose_name="日間リクエスト数制限"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="このレコードを作成したユーザー",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="作成者",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="このレコードを最後に更新したユーザー",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="更新者",
                    ),
                ),
            ],
            options={
                "verbose_name": "スクレイピング対象サイト",
                "verbose_name_plural": "スクレイピング対象サイト",
            },
        ),
        migrations.CreateModel(
            name="RateLimitLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="レコードが作成された日時",
                        verbose_name="作成日時",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="レコードが最後に更新された日時",
                        verbose_name="更新日時",
                    ),
                ),
                ("requests_count", models.IntegerField(verbose_name="リクエスト数")),
                ("time_window", models.DurationField(verbose_name="時間窓")),
                (
                    "is_limit_exceeded",
                    models.BooleanField(default=False, verbose_name="制限超過"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="このレコードを作成したユーザー",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="作成者",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="このレコードを最後に更新したユーザー",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="更新者",
                    ),
                ),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rate_logs",
                        to="scraping.scrapingsource",
                    ),
                ),
            ],
            options={
                "verbose_name": "レート制限ログ",
                "verbose_name_plural": "レート制限ログ",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ProxyServer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="レコードが作成された日時",
                        verbose_name="作成日時",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="レコードが最後に更新された日時",
                        verbose_name="更新日時",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="プロキシ名")),
                ("host", models.CharField(max_length=255, verbose_name="ホスト")),
                ("port", models.IntegerField(verbose_name="ポート")),
                (
                    "username",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="ユーザー名"
                    ),
                ),
                (
                    "password",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="パスワード"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="アクティブ"),
                ),
                (
                    "is_working",
                    models.BooleanField(default=True, verbose_name="動作中"),
                ),
                (
                    "success_count",
                    models.IntegerField(default=0, verbose_name="成功回数"),
                ),
                (
                    "failure_count",
                    models.IntegerField(default=0, verbose_name="失敗回数"),
                ),
                (
                    "last_used_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="最終使用時刻"
                    ),
                ),
                (
                    "last_check_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="最終チェック時刻"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="このレコードを作成したユーザー",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="作成者",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="このレコードを最後に更新したユーザー",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="更新者",
                    ),
                ),
            ],
            options={
                "verbose_name": "プロキシサーバー",
                "verbose_name_plural": "プロキシサーバー",
                "unique_together": {("host", "port")},
            },
        ),
        migrations.CreateModel(
            name="ScrapingRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="レコードが作成された日時",
                        verbose_name="作成日時",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="レコードが最後に更新された日時",
                        verbose_name="更新日時",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="ルール名")),
                (
                    "rule_type",
                    models.CharField(
                        choices=[
                            ("css_selector", "CSSセレクター"),
                            ("xpath", "XPath"),
                            ("regex", "正規表現"),
                            ("json_path", "JSONPath"),
                        ],
                        max_length=20,
                        verbose_name="ルール種別",
                    ),
                ),
                ("selector", models.TextField(verbose_name="セレクター")),
                (
                    "attribute",
                    models.CharField(blank=True, max_length=50, verbose_name="属性名"),
                ),
                (
                    "field_name",
                    models.CharField(max_length=50, verbose_name="フィールド名"),
                ),
                (
                    "data_type",
                    models.CharField(
                        choices=[
                            ("text", "テキスト"),
                            ("number", "数値"),
                            ("date", "日付"),
                            ("url", "URL"),
                            ("boolean", "真偽値"),
                        ],
                        default="text",
                        max_length=20,
                        verbose_name="データ型",
                    ),
                ),
                (
                    "preprocessing_rules",
                    models.JSONField(
                        blank=True, default=list, verbose_name="前処理ルール"
                    ),
                ),
                (
                    "validation_rules",
                    models.JSONField(
                        blank=True, default=list, verbose_name="バリデーションルール"
                    ),
                ),
                (
                    "is_required",
                    models.BooleanField(default=False, verbose_name="必須項目"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="アクティブ"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="このレコードを作成したユーザー",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="作成者",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="このレコードを最後に更新したユーザー",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="更新者",
                    ),
                ),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rules",
                        to="scraping.scrapingsource",
                    ),
                ),
            ],
            options={
                "verbose_name": "スクレイピングルール",
                "verbose_name_plural": "スクレイピングルール",
                "unique_together": {("source", "field_name")},
            },
        ),
    ]
