# Generated by Django 5.1.4 on 2025-09-23 08:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("horses", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Race",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="レコードが作成された日時",
                        verbose_name="作成日時",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="レコードが最後に更新された日時",
                        verbose_name="更新日時",
                    ),
                ),
                (
                    "race_id",
                    models.CharField(
                        max_length=12, unique=True, verbose_name="レースID"
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="レース名")),
                ("race_date", models.DateField(verbose_name="開催日")),
                ("race_number", models.IntegerField(verbose_name="レース番号")),
                (
                    "race_class",
                    models.CharField(
                        choices=[
                            ("novice", "新馬"),
                            ("maiden", "未勝利"),
                            ("1win", "1勝クラス"),
                            ("2win", "2勝クラス"),
                            ("3win", "3勝クラス"),
                            ("listed", "リステッド"),
                            ("g3", "G3"),
                            ("g2", "G2"),
                            ("g1", "G1"),
                            ("special", "特別レース"),
                        ],
                        max_length=20,
                        verbose_name="レースクラス",
                    ),
                ),
                ("distance", models.IntegerField(verbose_name="距離（メートル）")),
                (
                    "track_type",
                    models.CharField(
                        choices=[("turf", "芝"), ("dirt", "ダート"), ("jump", "障害")],
                        max_length=10,
                        verbose_name="コース種別",
                    ),
                ),
                (
                    "track_condition",
                    models.CharField(
                        choices=[
                            ("firm", "良"),
                            ("good", "稍重"),
                            ("yielding", "重"),
                            ("soft", "不良"),
                        ],
                        max_length=20,
                        verbose_name="馬場状態",
                    ),
                ),
                (
                    "weather",
                    models.CharField(
                        choices=[
                            ("fine", "晴"),
                            ("cloudy", "曇"),
                            ("rainy", "雨"),
                            ("snowy", "雪"),
                        ],
                        max_length=20,
                        verbose_name="天候",
                    ),
                ),
                ("start_time", models.TimeField(verbose_name="発走時刻")),
                (
                    "prize_money",
                    models.BigIntegerField(default=0, verbose_name="賞金（円）"),
                ),
                (
                    "entry_count",
                    models.IntegerField(default=0, verbose_name="出走頭数"),
                ),
                (
                    "is_grade_race",
                    models.BooleanField(default=False, verbose_name="重賞レース"),
                ),
                (
                    "is_completed",
                    models.BooleanField(default=False, verbose_name="レース終了"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="このレコードを作成したユーザー",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="作成者",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="このレコードを最後に更新したユーザー",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="更新者",
                    ),
                ),
            ],
            options={
                "verbose_name": "レース",
                "verbose_name_plural": "レース",
            },
        ),
        migrations.CreateModel(
            name="RaceEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="レコードが作成された日時",
                        verbose_name="作成日時",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="レコードが最後に更新された日時",
                        verbose_name="更新日時",
                    ),
                ),
                ("horse_number", models.IntegerField(verbose_name="馬番")),
                ("frame_number", models.IntegerField(verbose_name="枠番")),
                ("weight", models.FloatField(verbose_name="斤量")),
                (
                    "horse_weight",
                    models.IntegerField(blank=True, null=True, verbose_name="馬体重"),
                ),
                (
                    "weight_change",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="馬体重増減"
                    ),
                ),
                (
                    "win_odds",
                    models.FloatField(blank=True, null=True, verbose_name="単勝オッズ"),
                ),
                (
                    "place_odds",
                    models.FloatField(blank=True, null=True, verbose_name="複勝オッズ"),
                ),
                (
                    "popularity",
                    models.IntegerField(blank=True, null=True, verbose_name="人気"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="このレコードを作成したユーザー",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="作成者",
                    ),
                ),
                (
                    "horse",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="horses.horse"
                    ),
                ),
                (
                    "jockey",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="horses.jockey"
                    ),
                ),
                (
                    "race",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="entries",
                        to="races.race",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="このレコードを最後に更新したユーザー",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="更新者",
                    ),
                ),
            ],
            options={
                "verbose_name": "出走馬",
                "verbose_name_plural": "出走馬",
                "unique_together": {("race", "horse_number")},
            },
        ),
        migrations.CreateModel(
            name="RaceResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="レコードが作成された日時",
                        verbose_name="作成日時",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="レコードが最後に更新された日時",
                        verbose_name="更新日時",
                    ),
                ),
                ("finish_position", models.IntegerField(verbose_name="着順")),
                (
                    "finish_time",
                    models.CharField(blank=True, max_length=20, verbose_name="タイム"),
                ),
                (
                    "time_difference",
                    models.CharField(blank=True, max_length=20, verbose_name="着差"),
                ),
                (
                    "corner_positions",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="コーナー通過順"
                    ),
                ),
                (
                    "win_payout",
                    models.IntegerField(blank=True, null=True, verbose_name="単勝配当"),
                ),
                (
                    "place_payout",
                    models.IntegerField(blank=True, null=True, verbose_name="複勝配当"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="このレコードを作成したユーザー",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="作成者",
                    ),
                ),
                (
                    "entry",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="result",
                        to="races.raceentry",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="このレコードを最後に更新したユーザー",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="更新者",
                    ),
                ),
            ],
            options={
                "verbose_name": "レース結果",
                "verbose_name_plural": "レース結果",
            },
        ),
        migrations.CreateModel(
            name="Venue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="レコードが作成された日時",
                        verbose_name="作成日時",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="レコードが最後に更新された日時",
                        verbose_name="更新日時",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="競馬場名"
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        max_length=10, unique=True, verbose_name="競馬場コード"
                    ),
                ),
                ("location", models.CharField(max_length=100, verbose_name="所在地")),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="このレコードを作成したユーザー",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="作成者",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="このレコードを最後に更新したユーザー",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="更新者",
                    ),
                ),
            ],
            options={
                "verbose_name": "競馬場",
                "verbose_name_plural": "競馬場",
            },
        ),
        migrations.AddField(
            model_name="race",
            name="venue",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="races.venue",
                verbose_name="競馬場",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="race",
            unique_together={("venue", "race_date", "race_number")},
        ),
    ]
