# Generated by Django 5.1.4 on 2024-12-27 00:17

import django.contrib.auth.models
import django.contrib.auth.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompareView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('race_id', models.CharField(db_comment='レースID', help_text='レースID', max_length=12)),
                ('horse_number', models.CharField(db_comment='馬番', help_text='馬番', max_length=5)),
                ('race_date', models.DateField(db_comment='レース日付', help_text='レース日付')),
            ],
            options={
                'db_table': 'compare_view',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='URLData',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('race_id', models.CharField(db_comment='レースID', help_text='レースID', max_length=12)),
                ('race_date', models.DateTimeField(db_comment='レース日付', help_text='レース日付')),
                ('url', models.CharField(db_comment='URL', help_text='URL')),
                ('created_at', models.DateTimeField(db_comment='作成日時', help_text='作成日時')),
                ('updated_at', models.DateTimeField(db_comment='更新日時', help_text='更新日時')),
                ('created_user', models.CharField(db_comment='作成ユーザーID', help_text='作成ユーザーID', max_length=255, null=True)),
                ('updated_user', models.CharField(db_comment='更新ユーザーID', help_text='更新ユーザーID', max_length=255, null=True)),
            ],
            options={
                'db_table': 'url_mst',
                'ordering': ['race_date', 'race_id'],
            },
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='BaseData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('race_id', models.CharField(db_comment='レースID', help_text='レースID', max_length=12)),
                ('horse_number', models.CharField(db_comment='馬番', help_text='馬番', max_length=5)),
                ('horse_name', models.CharField(db_comment='馬名', help_text='馬名', max_length=255)),
                ('race_date', models.DateField(db_comment='レース日付', help_text='レース日付')),
                ('event_title', models.CharField(db_comment='レース名', help_text='レース名', max_length=255, null=True)),
                ('frame_number', models.CharField(db_comment='枠番号', help_text='枠番号', max_length=5, null=True)),
                ('sex', models.CharField(db_comment='性別', help_text='性別', max_length=10, null=True)),
                ('weight', models.CharField(db_comment='斤量', help_text='斤量', null=True)),
                ('body_weight', models.CharField(db_comment='馬体重', help_text='馬体重', null=True)),
                ('jockey_name', models.CharField(db_comment='騎手名', help_text='騎手名', max_length=255, null=True)),
                ('stable_name', models.CharField(db_comment='厩舎名', help_text='厩舎名', max_length=255, null=True)),
                ('weight_change', models.CharField(db_comment='馬体重の増減', help_text='馬体重の増減', null=True)),
                ('odds', models.CharField(db_comment='オッズ', help_text='オッズ', null=True)),
                ('popularity', models.CharField(db_comment='人気順', help_text='人気順', null=True)),
                ('is_shinba', models.BooleanField(db_comment='新馬戦フラグ', default=False, help_text='新馬戦フラグ')),
                ('is_mishori', models.BooleanField(db_comment='未勝利戦フラグ', default=False, help_text='未勝利戦フラグ')),
                ('is_1win', models.BooleanField(db_comment='1勝フラグ', default=False, help_text='1勝フラグ')),
                ('is_2win', models.BooleanField(db_comment='2勝フラグ', default=False, help_text='2勝フラグ')),
                ('is_3win', models.BooleanField(db_comment='3勝フラグ', default=False, help_text='3勝フラグ')),
                ('is_g3', models.BooleanField(db_comment='G3フラグ', default=False, help_text='G3フラグ')),
                ('is_g2', models.BooleanField(db_comment='G2フラグ', default=False, help_text='G2フラグ')),
                ('is_g1', models.BooleanField(db_comment='G1フラグ', default=False, help_text='G1フラグ')),
                ('is_l', models.BooleanField(db_comment='Lクラスフラグ', default=False, help_text='Lクラスフラグ')),
                ('is_op', models.BooleanField(db_comment='OPクラスフラグ', default=False, help_text='OPクラスフラグ')),
                ('is_win5', models.BooleanField(db_comment='Win5対象フラグ', default=False, help_text='Win5対象フラグ')),
                ('race_place', models.CharField(db_comment='開催場所', help_text='開催場所', max_length=255, null=True)),
                ('created_at', models.DateTimeField(db_comment='作成日時', help_text='作成日時')),
                ('updated_at', models.DateTimeField(db_comment='更新日時', help_text='更新日時')),
                ('created_user', models.CharField(db_comment='作成ユーザーID', help_text='作成ユーザーID', max_length=255, null=True)),
                ('updated_user', models.CharField(db_comment='更新ユーザーID', help_text='更新ユーザーID', max_length=255, null=True)),
            ],
            options={
                'db_table': 'base_info',
                'ordering': ['race_date', 'race_date', 'horse_number'],
                'constraints': [models.UniqueConstraint(fields=('race_id', 'horse_number'), name='unique_base_info')],
            },
        ),
        migrations.CreateModel(
            name='HorseData',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('race_id', models.CharField(db_comment='レースID', help_text='レースID', max_length=12)),
                ('horse_number', models.CharField(db_comment='馬番', help_text='馬番', max_length=5)),
                ('horse_name', models.CharField(db_comment='馬名', help_text='馬名', max_length=255)),
                ('sire_1_male', models.CharField(db_comment='血統1世代目の雄', help_text='血統1世代目の雄', max_length=255, null=True)),
                ('sire_1_female', models.CharField(db_comment='血統1世代目の雌', help_text='血統1世代目の雌', max_length=255, null=True)),
                ('sire_2_1_male', models.CharField(db_comment='血統2-1世代目の雄', help_text='血統2-1世代目の雄', max_length=255, null=True)),
                ('sire_2_1_female', models.CharField(db_comment='血統2-1世代目の雌', help_text='血統2-1世代目の雌', max_length=255, null=True)),
                ('sire_2_2_male', models.CharField(db_comment='血統2-2世代目の雄', help_text='血統2-2世代目の雄', max_length=255, null=True)),
                ('sire_2_2_female', models.CharField(db_comment='血統2-2世代目の雌', help_text='血統2-2世代目の雌', max_length=255, null=True)),
                ('created_at', models.DateTimeField(db_comment='作成日時', help_text='作成日時')),
                ('updated_at', models.DateTimeField(db_comment='更新日時', help_text='更新日時')),
                ('created_user', models.CharField(db_comment='作成ユーザーID', help_text='作成ユーザーID', max_length=255, null=True)),
                ('updated_user', models.CharField(db_comment='更新ユーザーID', help_text='更新ユーザーID', max_length=255, null=True)),
            ],
            options={
                'db_table': 'horse_info',
                'constraints': [models.UniqueConstraint(fields=('race_id', 'horse_number'), name='unique_horse_info')],
            },
        ),
        migrations.CreateModel(
            name='ResultData',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('race_id', models.CharField(db_comment='レースID', help_text='レースID', max_length=12)),
                ('horse_number', models.CharField(db_comment='馬番', help_text='馬番', max_length=5)),
                ('horse_name', models.CharField(db_comment='馬名', help_text='馬名', max_length=255)),
                ('rank', models.CharField(db_comment='着順', help_text='着順', max_length=10)),
                ('race_time', models.CharField(db_comment='タイム', help_text='タイム', max_length=20)),
                ('corner_order', models.CharField(db_comment='コーナー通過順', help_text='コーナー通過順', max_length=50)),
                ('race_date', models.DateField(db_comment='レース日付', help_text='レース日付')),
                ('positions', models.CharField(db_comment='レース順位', default='', help_text='レース順位', max_length=10)),
                ('positions_tie', models.CharField(db_comment='同率レース順位', help_text='同率レース順位', max_length=10, null=True)),
                ('pay1', models.CharField(db_comment='単勝', default='', help_text='単勝', max_length=30)),
                ('pay1_tie', models.CharField(db_comment='同率単勝', help_text='同率単勝', max_length=30, null=True)),
                ('pay123_1', models.CharField(db_comment='複勝1', default='', help_text='複勝1', max_length=30)),
                ('pay123_2', models.CharField(db_comment='複勝2', default='', help_text='複勝2', max_length=30)),
                ('pay123_3', models.CharField(db_comment='複勝1', default='', help_text='複勝1', max_length=30)),
                ('pay123_tie', models.CharField(db_comment='同率複勝1', help_text='同率複勝1', max_length=30, null=True)),
                ('pay123_12_1', models.CharField(db_comment='ワイド1', default='', help_text='ワイド1', max_length=30)),
                ('pay123_12_2', models.CharField(db_comment='ワイド2', default='', help_text='ワイド2', max_length=30)),
                ('pay123_12_3', models.CharField(db_comment='ワイド3', default='', help_text='ワイド3', max_length=30)),
                ('pay123_12_4_tie', models.CharField(db_comment='同率ワイド2', help_text='同率ワイド2', max_length=30, null=True)),
                ('pay123_12_5_tie', models.CharField(db_comment='同率ワイド3', help_text='同率ワイド3', max_length=30, null=True)),
                ('pay12_21', models.CharField(db_comment='馬連', default='', help_text='馬連', max_length=30)),
                ('pay12_21_tie', models.CharField(db_comment='同率馬連', help_text='同率馬連', max_length=30, null=True)),
                ('pay12_12', models.CharField(db_comment='馬単', default='', help_text='馬単', max_length=30)),
                ('pay12_12_tie', models.CharField(db_comment='同率馬単', help_text='同率馬単', max_length=30, null=True)),
                ('pay123_321', models.CharField(db_comment='3連複', default='', help_text='3連複', max_length=30)),
                ('pay123_321_tie', models.CharField(db_comment='同率3連複', help_text='同率3連複', max_length=30, null=True)),
                ('pay123_123', models.CharField(db_comment='3連単', default='', help_text='3連単', max_length=30)),
                ('pay123_123_tie', models.CharField(db_comment='同率3連単', help_text='同率3連単', max_length=30, null=True)),
                ('created_at', models.DateTimeField(db_comment='作成日時', help_text='作成日時')),
                ('updated_at', models.DateTimeField(db_comment='更新日時', help_text='更新日時')),
                ('created_user', models.CharField(db_comment='作成ユーザーID', help_text='作成ユーザーID', max_length=255, null=True)),
                ('updated_user', models.CharField(db_comment='更新ユーザーID', help_text='更新ユーザーID', max_length=255, null=True)),
            ],
            options={
                'db_table': 'result_info',
                'ordering': ['race_date', 'race_date', 'horse_number'],
                'constraints': [models.UniqueConstraint(fields=('race_id', 'horse_number'), name='unique_result_info')],
            },
        ),
    ]
