# Generated by Django 5.1.4 on 2025-01-11 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_folder', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MissingRaceIds',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('race_id', models.CharField(db_comment='レースID', help_text='レースID', max_length=12)),
                ('url', models.CharField(db_comment='URL', help_text='URL')),
            ],
            options={
                'db_table': 'v_create_race_ids',
                'managed': False,
            },
        ),
        migrations.RemoveConstraint(
            model_name='horsedata',
            name='unique_horse_info',
        ),
        migrations.RenameField(
            model_name='basedata',
            old_name='is_g1',
            new_name='g1_flg',
        ),
        migrations.RenameField(
            model_name='basedata',
            old_name='is_g2',
            new_name='g2_flg',
        ),
        migrations.RenameField(
            model_name='basedata',
            old_name='is_g3',
            new_name='g3_flg',
        ),
        migrations.RenameField(
            model_name='basedata',
            old_name='is_l',
            new_name='l_flg',
        ),
        migrations.RenameField(
            model_name='basedata',
            old_name='is_shinba',
            new_name='new_flg',
        ),
        migrations.RenameField(
            model_name='basedata',
            old_name='is_mishori',
            new_name='not_win_flg',
        ),
        migrations.RenameField(
            model_name='basedata',
            old_name='is_op',
            new_name='op_flg',
        ),
        migrations.RenameField(
            model_name='basedata',
            old_name='is_1win',
            new_name='win_1_flg',
        ),
        migrations.RenameField(
            model_name='basedata',
            old_name='is_2win',
            new_name='win_2_flg',
        ),
        migrations.RenameField(
            model_name='basedata',
            old_name='is_3win',
            new_name='win_3_flg',
        ),
        migrations.RemoveField(
            model_name='horsedata',
            name='horse_number',
        ),
        migrations.AddField(
            model_name='horsedata',
            name='body_weight_1',
            field=models.CharField(blank=True, db_comment='体重変動_1', help_text='体重変動_1', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='horsedata',
            name='body_weight_10',
            field=models.CharField(blank=True, db_comment='体重変動_10', help_text='体重変動_10', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='horsedata',
            name='body_weight_2',
            field=models.CharField(blank=True, db_comment='体重変動_2', help_text='体重変動_2', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='horsedata',
            name='body_weight_3',
            field=models.CharField(blank=True, db_comment='体重変動_3', help_text='体重変動_3', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='horsedata',
            name='body_weight_4',
            field=models.CharField(blank=True, db_comment='体重変動_4', help_text='体重変動_4', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='horsedata',
            name='body_weight_5',
            field=models.CharField(blank=True, db_comment='体重変動_5', help_text='体重変動_5', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='horsedata',
            name='body_weight_6',
            field=models.CharField(blank=True, db_comment='体重変動_6', help_text='体重変動_6', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='horsedata',
            name='body_weight_7',
            field=models.CharField(blank=True, db_comment='体重変動_7', help_text='体重変動_7', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='horsedata',
            name='body_weight_8',
            field=models.CharField(blank=True, db_comment='体重変動_8', help_text='体重変動_8', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='horsedata',
            name='body_weight_9',
            field=models.CharField(blank=True, db_comment='体重変動_9', help_text='体重変動_9', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='horsedata',
            name='count_1',
            field=models.CharField(blank=True, db_comment='頭数_1', help_text='頭数_1', max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='horsedata',
            name='count_10',
            field=models.CharField(blank=True, db_comment='頭数_10', help_text='頭数_10', max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='horsedata',
            name='count_2',
            field=models.CharField(blank=True, db_comment='頭数_2', help_text='頭数_2', max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='horsedata',
            name='count_3',
            field=models.CharField(blank=True, db_comment='頭数_3', help_text='頭数_3', max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='horsedata',
            name='count_4',
            field=models.CharField(blank=True, db_comment='頭数_4', help_text='頭数_4', max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='horsedata',
            name='count_5',
            field=models.CharField(blank=True, db_comment='頭数_5', help_text='頭数_5', max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='horsedata',
            name='count_6',
            field=models.CharField(blank=True, db_comment='頭数_6', help_text='頭数_6', max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='horsedata',
            name='count_7',
            field=models.CharField(blank=True, db_comment='頭数_7', help_text='頭数_7', max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='horsedata',
            name='count_8',
            field=models.CharField(blank=True, db_comment='頭数_8', help_text='頭数_8', max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='horsedata',
            name='count_9',
            field=models.CharField(blank=True, db_comment='頭数_9', help_text='頭数_9', max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='horsedata',
            name='distance_1',
            field=models.CharField(blank=True, db_comment='距離_1', help_text='距離_1', null=True),
        ),
        migrations.AddField(
            model_name='horsedata',
            name='distance_10',
            field=models.CharField(blank=True, db_comment='距離_10', help_text='距離_10', null=True),
        ),
        migrations.AddField(
            model_name='horsedata',
            name='distance_2',
            field=models.CharField(blank=True, db_comment='距離_2', help_text='距離_2', null=True),
        ),
        migrations.AddField(
            model_name='horsedata',
            name='distance_3',
            field=models.CharField(blank=True, db_comment='距離_3', help_text='距離_3', null=True),
        ),
        migrations.AddField(
            model_name='horsedata',
            name='distance_4',
            field=models.CharField(blank=True, db_comment='距離_4', help_text='距離_4', null=True),
        ),
        migrations.AddField(
            model_name='horsedata',
            name='distance_5',
            field=models.CharField(blank=True, db_comment='距離_5', help_text='距離_5', null=True),
        ),
        migrations.AddField(
            model_name='horsedata',
            name='distance_6',
            field=models.CharField(blank=True, db_comment='距離_6', help_text='距離_6', null=True),
        ),
        migrations.AddField(
            model_name='horsedata',
            name='distance_7',
            field=models.CharField(blank=True, db_comment='距離_7', help_text='距離_7', null=True),
        ),
        migrations.AddField(
            model_name='horsedata',
            name='distance_8',
            field=models.CharField(blank=True, db_comment='距離_8', help_text='距離_8', null=True),
        ),
        migrations.AddField(
            model_name='horsedata',
            name='distance_9',
            field=models.CharField(blank=True, db_comment='距離_9', help_text='距離_9', null=True),
        ),
        migrations.AddField(
            model_name='horsedata',
            name='finish_1',
            field=models.CharField(blank=True, db_comment='着差_1', help_text='着差_1', null=True),
        ),
        migrations.AddField(
            model_name='horsedata',
            name='finish_10',
            field=models.CharField(blank=True, db_comment='着差_10', help_text='着差_10', null=True),
        ),
        migrations.AddField(
            model_name='horsedata',
            name='finish_2',
            field=models.CharField(blank=True, db_comment='着差_2', help_text='着差_2', null=True),
        ),
        migrations.AddField(
            model_name='horsedata',
            name='finish_3',
            field=models.CharField(blank=True, db_comment='着差_3', help_text='着差_3', null=True),
        ),
        migrations.AddField(
            model_name='horsedata',
            name='finish_4',
            field=models.CharField(blank=True, db_comment='着差_4', help_text='着差_4', null=True),
        ),
        migrations.AddField(
            model_name='horsedata',
            name='finish_5',
            field=models.CharField(blank=True, db_comment='着差_5', help_text='着差_5', null=True),
        ),
        migrations.AddField(
            model_name='horsedata',
            name='finish_6',
            field=models.CharField(blank=True, db_comment='着差_6', help_text='着差_6', null=True),
        ),
        migrations.AddField(
            model_name='horsedata',
            name='finish_7',
            field=models.CharField(blank=True, db_comment='着差_7', help_text='着差_7', null=True),
        ),
        migrations.AddField(
            model_name='horsedata',
            name='finish_8',
            field=models.CharField(blank=True, db_comment='着差_8', help_text='着差_8', null=True),
        ),
        migrations.AddField(
            model_name='horsedata',
            name='finish_9',
            field=models.CharField(blank=True, db_comment='着差_9', help_text='着差_9', null=True),
        ),
        migrations.AddField(
            model_name='horsedata',
            name='frame_1',
            field=models.CharField(blank=True, db_comment='枠番号_1', help_text='枠番号_1', max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='horsedata',
            name='frame_10',
            field=models.CharField(blank=True, db_comment='枠番号_10', help_text='枠番号_10', max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='horsedata',
            name='frame_2',
            field=models.CharField(blank=True, db_comment='枠番号_2', help_text='枠番号_2', max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='horsedata',
            name='frame_3',
            field=models.CharField(blank=True, db_comment='枠番号_3', help_text='枠番号_3', max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='horsedata',
            name='frame_4',
            field=models.CharField(blank=True, db_comment='枠番号_4', help_text='枠番号_4', max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='horsedata',
            name='frame_5',
            field=models.CharField(blank=True, db_comment='枠番号_5', help_text='枠番号_5', max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='horsedata',
            name='frame_6',
            field=models.CharField(blank=True, db_comment='枠番号_6', help_text='枠番号_6', max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='horsedata',
            name='frame_7',
            field=models.CharField(blank=True, db_comment='枠番号_7', help_text='枠番号_7', max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='horsedata',
            name='frame_8',
            field=models.CharField(blank=True, db_comment='枠番号_8', help_text='枠番号_8', max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='horsedata',
            name='frame_9',
            field=models.CharField(blank=True, db_comment='枠番号_9', help_text='枠番号_9', max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='horsedata',
            name='g1_flg_1',
            field=models.BooleanField(db_comment='G1フラグ_1', default=False, help_text='G1フラグ_1'),
        ),
        migrations.AddField(
            model_name='horsedata',
            name='g1_flg_10',
            field=models.BooleanField(db_comment='G1フラグ_10', default=False, help_text='G1フラグ_10'),
        ),
        migrations.AddField(
            model_name='horsedata',
            name='g1_flg_2',
            field=models.BooleanField(db_comment='G1フラグ_2', default=False, help_text='G1フラグ_2'),
        ),
        migrations.AddField(
            model_name='horsedata',
            name='g1_flg_3',
            field=models.BooleanField(db_comment='G1フラグ_3', default=False, help_text='G1フラグ_3'),
        ),
        migrations.AddField(
            model_name='horsedata',
            name='g1_flg_4',
            field=models.BooleanField(db_comment='G1フラグ_4', default=False, help_text='G1フラグ_4'),
        ),
        migrations.AddField(
            model_name='horsedata',
            name='g1_flg_5',
            field=models.BooleanField(db_comment='G1フラグ_5', default=False, help_text='G1フラグ_5'),
        ),
        migrations.AddField(
            model_name='horsedata',
            name='g1_flg_6',
            field=models.BooleanField(db_comment='G1フラグ_6', default=False, help_text='G1フラグ_6'),
        ),
        migrations.AddField(
            model_name='horsedata',
            name='g1_flg_7',
            field=models.BooleanField(db_comment='G1フラグ_7', default=False, help_text='G1フラグ_7'),
        ),
        migrations.AddField(
            model_name='horsedata',
            name='g1_flg_8',
            field=models.BooleanField(db_comment='G1フラグ_8', default=False, help_text='G1フラグ_8'),
        ),
        migrations.AddField(
            model_name='horsedata',
            name='g1_flg_9',
            field=models.BooleanField(db_comment='G1フラグ_9', default=False, help_text='G1フラグ_9'),
        ),
        migrations.AddField(
            model_name='horsedata',
            name='g2_flg_1',
            field=models.BooleanField(db_comment='G2フラグ_1', default=False, help_text='G2フラグ_1'),
        ),
        migrations.AddField(
            model_name='horsedata',
            name='g2_flg_10',
            field=models.BooleanField(db_comment='G2フラグ_10', default=False, help_text='G2フラグ_10'),
        ),
        migrations.AddField(
            model_name='horsedata',
            name='g2_flg_2',
            field=models.BooleanField(db_comment='G2フラグ_2', default=False, help_text='G2フラグ_2'),
        ),
        migrations.AddField(
            model_name='horsedata',
            name='g2_flg_3',
            field=models.BooleanField(db_comment='G2フラグ_3', default=False, help_text='G2フラグ_3'),
        ),
        migrations.AddField(
            model_name='horsedata',
            name='g2_flg_4',
            field=models.BooleanField(db_comment='G2フラグ_4', default=False, help_text='G2フラグ_4'),
        ),
        migrations.AddField(
            model_name='horsedata',
            name='g2_flg_5',
            field=models.BooleanField(db_comment='G2フラグ_5', default=False, help_text='G2フラグ_5'),
        ),
        migrations.AddField(
            model_name='horsedata',
            name='g2_flg_6',
            field=models.BooleanField(db_comment='G2フラグ_6', default=False, help_text='G2フラグ_6'),
        ),
        migrations.AddField(
            model_name='horsedata',
            name='g2_flg_7',
            field=models.BooleanField(db_comment='G2フラグ_7', default=False, help_text='G2フラグ_7'),
        ),
        migrations.AddField(
            model_name='horsedata',
            name='g2_flg_8',
            field=models.BooleanField(db_comment='G2フラグ_8', default=False, help_text='G2フラグ_8'),
        ),
        migrations.AddField(
            model_name='horsedata',
            name='g2_flg_9',
            field=models.BooleanField(db_comment='G2フラグ_9', default=False, help_text='G2フラグ_9'),
        ),
        migrations.AddField(
            model_name='horsedata',
            name='g3_flg_1',
            field=models.BooleanField(db_comment='G3フラグ_1', default=False, help_text='G3フラグ_1'),
        ),
        migrations.AddField(
            model_name='horsedata',
            name='g3_flg_10',
            field=models.BooleanField(db_comment='G3フラグ_10', default=False, help_text='G3フラグ_10'),
        ),
        migrations.AddField(
            model_name='horsedata',
            name='g3_flg_2',
            field=models.BooleanField(db_comment='G3フラグ_2', default=False, help_text='G3フラグ_2'),
        ),
        migrations.AddField(
            model_name='horsedata',
            name='g3_flg_3',
            field=models.BooleanField(db_comment='G3フラグ_3', default=False, help_text='G3フラグ_3'),
        ),
        migrations.AddField(
            model_name='horsedata',
            name='g3_flg_4',
            field=models.BooleanField(db_comment='G3フラグ_4', default=False, help_text='G3フラグ_4'),
        ),
        migrations.AddField(
            model_name='horsedata',
            name='g3_flg_5',
            field=models.BooleanField(db_comment='G3フラグ_5', default=False, help_text='G3フラグ_5'),
        ),
        migrations.AddField(
            model_name='horsedata',
            name='g3_flg_6',
            field=models.BooleanField(db_comment='G3フラグ_6', default=False, help_text='G3フラグ_6'),
        ),
        migrations.AddField(
            model_name='horsedata',
            name='g3_flg_7',
            field=models.BooleanField(db_comment='G3フラグ_7', default=False, help_text='G3フラグ_7'),
        ),
        migrations.AddField(
            model_name='horsedata',
            name='g3_flg_8',
            field=models.BooleanField(db_comment='G3フラグ_8', default=False, help_text='G3フラグ_8'),
        ),
        migrations.AddField(
            model_name='horsedata',
            name='g3_flg_9',
            field=models.BooleanField(db_comment='G3フラグ_9', default=False, help_text='G3フラグ_9'),
        ),
        migrations.AddField(
            model_name='horsedata',
            name='horse_number_1',
            field=models.CharField(blank=True, db_comment='馬番_1', help_text='馬番_1', max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='horsedata',
            name='horse_number_10',
            field=models.CharField(blank=True, db_comment='馬番_10', help_text='馬番_10', max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='horsedata',
            name='horse_number_2',
            field=models.CharField(blank=True, db_comment='馬番_2', help_text='馬番_2', max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='horsedata',
            name='horse_number_3',
            field=models.CharField(blank=True, db_comment='馬番_3', help_text='馬番_3', max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='horsedata',
            name='horse_number_4',
            field=models.CharField(blank=True, db_comment='馬番_4', help_text='馬番_4', max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='horsedata',
            name='horse_number_5',
            field=models.CharField(blank=True, db_comment='馬番_5', help_text='馬番_5', max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='horsedata',
            name='horse_number_6',
            field=models.CharField(blank=True, db_comment='馬番_6', help_text='馬番_6', max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='horsedata',
            name='horse_number_7',
            field=models.CharField(blank=True, db_comment='馬番_7', help_text='馬番_7', max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='horsedata',
            name='horse_number_8',
            field=models.CharField(blank=True, db_comment='馬番_8', help_text='馬番_8', max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='horsedata',
            name='horse_number_9',
            field=models.CharField(blank=True, db_comment='馬番_9', help_text='馬番_9', max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='horsedata',
            name='jockey_1',
            field=models.CharField(blank=True, db_comment='騎手名_1', help_text='騎手名_1', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='horsedata',
            name='jockey_10',
            field=models.CharField(blank=True, db_comment='騎手名_10', help_text='騎手名_10', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='horsedata',
            name='jockey_2',
            field=models.CharField(blank=True, db_comment='騎手名_2', help_text='騎手名_2', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='horsedata',
            name='jockey_3',
            field=models.CharField(blank=True, db_comment='騎手名_3', help_text='騎手名_3', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='horsedata',
            name='jockey_4',
            field=models.CharField(blank=True, db_comment='騎手名_4', help_text='騎手名_4', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='horsedata',
            name='jockey_5',
            field=models.CharField(blank=True, db_comment='騎手名_5', help_text='騎手名_5', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='horsedata',
            name='jockey_6',
            field=models.CharField(blank=True, db_comment='騎手名_6', help_text='騎手名_6', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='horsedata',
            name='jockey_7',
            field=models.CharField(blank=True, db_comment='騎手名_7', help_text='騎手名_7', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='horsedata',
            name='jockey_8',
            field=models.CharField(blank=True, db_comment='騎手名_8', help_text='騎手名_8', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='horsedata',
            name='jockey_9',
            field=models.CharField(blank=True, db_comment='騎手名_9', help_text='騎手名_9', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='horsedata',
            name='l_flg_1',
            field=models.BooleanField(db_comment='lフラグ_1', default=False, help_text='lフラグ_1'),
        ),
        migrations.AddField(
            model_name='horsedata',
            name='l_flg_10',
            field=models.BooleanField(db_comment='lフラグ_10', default=False, help_text='lフラグ_10'),
        ),
        migrations.AddField(
            model_name='horsedata',
            name='l_flg_2',
            field=models.BooleanField(db_comment='lフラグ_2', default=False, help_text='lフラグ_2'),
        ),
        migrations.AddField(
            model_name='horsedata',
            name='l_flg_3',
            field=models.BooleanField(db_comment='lフラグ_3', default=False, help_text='lフラグ_3'),
        ),
        migrations.AddField(
            model_name='horsedata',
            name='l_flg_4',
            field=models.BooleanField(db_comment='lフラグ_4', default=False, help_text='lフラグ_4'),
        ),
        migrations.AddField(
            model_name='horsedata',
            name='l_flg_5',
            field=models.BooleanField(db_comment='lフラグ_5', default=False, help_text='lフラグ_5'),
        ),
        migrations.AddField(
            model_name='horsedata',
            name='l_flg_6',
            field=models.BooleanField(db_comment='lフラグ_6', default=False, help_text='lフラグ_6'),
        ),
        migrations.AddField(
            model_name='horsedata',
            name='l_flg_7',
            field=models.BooleanField(db_comment='lフラグ_7', default=False, help_text='lフラグ_7'),
        ),
        migrations.AddField(
            model_name='horsedata',
            name='l_flg_8',
            field=models.BooleanField(db_comment='lフラグ_8', default=False, help_text='lフラグ_8'),
        ),
        migrations.AddField(
            model_name='horsedata',
            name='l_flg_9',
            field=models.BooleanField(db_comment='lフラグ_9', default=False, help_text='lフラグ_9'),
        ),
        migrations.AddField(
            model_name='horsedata',
            name='new_flg_1',
            field=models.BooleanField(db_comment='新馬戦フラグ_1', default=False, help_text='新馬戦フラグ_1'),
        ),
        migrations.AddField(
            model_name='horsedata',
            name='new_flg_10',
            field=models.BooleanField(db_comment='新馬戦フラグ_10', default=False, help_text='新馬戦フラグ_10'),
        ),
        migrations.AddField(
            model_name='horsedata',
            name='new_flg_2',
            field=models.BooleanField(db_comment='新馬戦フラグ_2', default=False, help_text='新馬戦フラグ_2'),
        ),
        migrations.AddField(
            model_name='horsedata',
            name='new_flg_3',
            field=models.BooleanField(db_comment='新馬戦フラグ_3', default=False, help_text='新馬戦フラグ_3'),
        ),
        migrations.AddField(
            model_name='horsedata',
            name='new_flg_4',
            field=models.BooleanField(db_comment='新馬戦フラグ_4', default=False, help_text='新馬戦フラグ_4'),
        ),
        migrations.AddField(
            model_name='horsedata',
            name='new_flg_5',
            field=models.BooleanField(db_comment='新馬戦フラグ_5', default=False, help_text='新馬戦フラグ_5'),
        ),
        migrations.AddField(
            model_name='horsedata',
            name='new_flg_6',
            field=models.BooleanField(db_comment='新馬戦フラグ_6', default=False, help_text='新馬戦フラグ_6'),
        ),
        migrations.AddField(
            model_name='horsedata',
            name='new_flg_7',
            field=models.BooleanField(db_comment='新馬戦フラグ_7', default=False, help_text='新馬戦フラグ_7'),
        ),
        migrations.AddField(
            model_name='horsedata',
            name='new_flg_8',
            field=models.BooleanField(db_comment='新馬戦フラグ_8', default=False, help_text='新馬戦フラグ_8'),
        ),
        migrations.AddField(
            model_name='horsedata',
            name='new_flg_9',
            field=models.BooleanField(db_comment='新馬戦フラグ_9', default=False, help_text='新馬戦フラグ_9'),
        ),
        migrations.AddField(
            model_name='horsedata',
            name='not_win_flg_1',
            field=models.BooleanField(db_comment='未勝利フラグ_1', default=False, help_text='未勝利フラグ_1'),
        ),
        migrations.AddField(
            model_name='horsedata',
            name='not_win_flg_10',
            field=models.BooleanField(db_comment='未勝利フラグ_10', default=False, help_text='未勝利フラグ_10'),
        ),
        migrations.AddField(
            model_name='horsedata',
            name='not_win_flg_2',
            field=models.BooleanField(db_comment='未勝利フラグ_2', default=False, help_text='未勝利フラグ_2'),
        ),
        migrations.AddField(
            model_name='horsedata',
            name='not_win_flg_3',
            field=models.BooleanField(db_comment='未勝利フラグ_3', default=False, help_text='未勝利フラグ_3'),
        ),
        migrations.AddField(
            model_name='horsedata',
            name='not_win_flg_4',
            field=models.BooleanField(db_comment='未勝利フラグ_4', default=False, help_text='未勝利フラグ_4'),
        ),
        migrations.AddField(
            model_name='horsedata',
            name='not_win_flg_5',
            field=models.BooleanField(db_comment='未勝利フラグ_5', default=False, help_text='未勝利フラグ_5'),
        ),
        migrations.AddField(
            model_name='horsedata',
            name='not_win_flg_6',
            field=models.BooleanField(db_comment='未勝利フラグ_6', default=False, help_text='未勝利フラグ_6'),
        ),
        migrations.AddField(
            model_name='horsedata',
            name='not_win_flg_7',
            field=models.BooleanField(db_comment='未勝利フラグ_7', default=False, help_text='未勝利フラグ_7'),
        ),
        migrations.AddField(
            model_name='horsedata',
            name='not_win_flg_8',
            field=models.BooleanField(db_comment='未勝利フラグ_8', default=False, help_text='未勝利フラグ_8'),
        ),
        migrations.AddField(
            model_name='horsedata',
            name='not_win_flg_9',
            field=models.BooleanField(db_comment='未勝利フラグ_9', default=False, help_text='未勝利フラグ_9'),
        ),
        migrations.AddField(
            model_name='horsedata',
            name='odds_1',
            field=models.CharField(blank=True, db_comment='オッズ_1', help_text='オッズ_1', null=True),
        ),
        migrations.AddField(
            model_name='horsedata',
            name='odds_10',
            field=models.CharField(blank=True, db_comment='オッズ_10', help_text='オッズ_10', null=True),
        ),
        migrations.AddField(
            model_name='horsedata',
            name='odds_2',
            field=models.CharField(blank=True, db_comment='オッズ_2', help_text='オッズ_2', null=True),
        ),
        migrations.AddField(
            model_name='horsedata',
            name='odds_3',
            field=models.CharField(blank=True, db_comment='オッズ_3', help_text='オッズ_3', null=True),
        ),
        migrations.AddField(
            model_name='horsedata',
            name='odds_4',
            field=models.CharField(blank=True, db_comment='オッズ_4', help_text='オッズ_4', null=True),
        ),
        migrations.AddField(
            model_name='horsedata',
            name='odds_5',
            field=models.CharField(blank=True, db_comment='オッズ_5', help_text='オッズ_5', null=True),
        ),
        migrations.AddField(
            model_name='horsedata',
            name='odds_6',
            field=models.CharField(blank=True, db_comment='オッズ_6', help_text='オッズ_6', null=True),
        ),
        migrations.AddField(
            model_name='horsedata',
            name='odds_7',
            field=models.CharField(blank=True, db_comment='オッズ_7', help_text='オッズ_7', null=True),
        ),
        migrations.AddField(
            model_name='horsedata',
            name='odds_8',
            field=models.CharField(blank=True, db_comment='オッズ_8', help_text='オッズ_8', null=True),
        ),
        migrations.AddField(
            model_name='horsedata',
            name='odds_9',
            field=models.CharField(blank=True, db_comment='オッズ_9', help_text='オッズ_9', null=True),
        ),
        migrations.AddField(
            model_name='horsedata',
            name='op_flg_1',
            field=models.BooleanField(db_comment='opフラグ_1', default=False, help_text='opフラグ_1'),
        ),
        migrations.AddField(
            model_name='horsedata',
            name='op_flg_10',
            field=models.BooleanField(db_comment='opフラグ_10', default=False, help_text='opフラグ_10'),
        ),
        migrations.AddField(
            model_name='horsedata',
            name='op_flg_2',
            field=models.BooleanField(db_comment='opフラグ_2', default=False, help_text='opフラグ_2'),
        ),
        migrations.AddField(
            model_name='horsedata',
            name='op_flg_3',
            field=models.BooleanField(db_comment='opフラグ_3', default=False, help_text='opフラグ_3'),
        ),
        migrations.AddField(
            model_name='horsedata',
            name='op_flg_4',
            field=models.BooleanField(db_comment='opフラグ_4', default=False, help_text='opフラグ_4'),
        ),
        migrations.AddField(
            model_name='horsedata',
            name='op_flg_5',
            field=models.BooleanField(db_comment='opフラグ_5', default=False, help_text='opフラグ_5'),
        ),
        migrations.AddField(
            model_name='horsedata',
            name='op_flg_6',
            field=models.BooleanField(db_comment='opフラグ_6', default=False, help_text='opフラグ_6'),
        ),
        migrations.AddField(
            model_name='horsedata',
            name='op_flg_7',
            field=models.BooleanField(db_comment='opフラグ_7', default=False, help_text='opフラグ_7'),
        ),
        migrations.AddField(
            model_name='horsedata',
            name='op_flg_8',
            field=models.BooleanField(db_comment='opフラグ_8', default=False, help_text='opフラグ_8'),
        ),
        migrations.AddField(
            model_name='horsedata',
            name='op_flg_9',
            field=models.BooleanField(db_comment='opフラグ_9', default=False, help_text='opフラグ_9'),
        ),
        migrations.AddField(
            model_name='horsedata',
            name='pace_1',
            field=models.CharField(blank=True, db_comment='ペース_1', help_text='ペース_1', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='horsedata',
            name='pace_10',
            field=models.CharField(blank=True, db_comment='ペース_10', help_text='ペース_10', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='horsedata',
            name='pace_2',
            field=models.CharField(blank=True, db_comment='ペース_2', help_text='ペース_2', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='horsedata',
            name='pace_3',
            field=models.CharField(blank=True, db_comment='ペース_3', help_text='ペース_3', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='horsedata',
            name='pace_4',
            field=models.CharField(blank=True, db_comment='ペース_4', help_text='ペース_4', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='horsedata',
            name='pace_5',
            field=models.CharField(blank=True, db_comment='ペース_5', help_text='ペース_5', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='horsedata',
            name='pace_6',
            field=models.CharField(blank=True, db_comment='ペース_6', help_text='ペース_6', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='horsedata',
            name='pace_7',
            field=models.CharField(blank=True, db_comment='ペース_7', help_text='ペース_7', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='horsedata',
            name='pace_8',
            field=models.CharField(blank=True, db_comment='ペース_8', help_text='ペース_8', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='horsedata',
            name='pace_9',
            field=models.CharField(blank=True, db_comment='ペース_9', help_text='ペース_9', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='horsedata',
            name='popularity_1',
            field=models.CharField(blank=True, db_comment='人気順_1', help_text='人気順_1', max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='horsedata',
            name='popularity_10',
            field=models.CharField(blank=True, db_comment='人気順_10', help_text='人気順_10', max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='horsedata',
            name='popularity_2',
            field=models.CharField(blank=True, db_comment='人気順_2', help_text='人気順_2', max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='horsedata',
            name='popularity_3',
            field=models.CharField(blank=True, db_comment='人気順_3', help_text='人気順_3', max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='horsedata',
            name='popularity_4',
            field=models.CharField(blank=True, db_comment='人気順_4', help_text='人気順_4', max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='horsedata',
            name='popularity_5',
            field=models.CharField(blank=True, db_comment='人気順_5', help_text='人気順_5', max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='horsedata',
            name='popularity_6',
            field=models.CharField(blank=True, db_comment='人気順_6', help_text='人気順_6', max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='horsedata',
            name='popularity_7',
            field=models.CharField(blank=True, db_comment='人気順_7', help_text='人気順_7', max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='horsedata',
            name='popularity_8',
            field=models.CharField(blank=True, db_comment='人気順_8', help_text='人気順_8', max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='horsedata',
            name='popularity_9',
            field=models.CharField(blank=True, db_comment='人気順_9', help_text='人気順_9', max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='horsedata',
            name='position_1',
            field=models.CharField(blank=True, db_comment='着順_1', help_text='着順_1', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='horsedata',
            name='position_10',
            field=models.CharField(blank=True, db_comment='着順_10', help_text='着順_10', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='horsedata',
            name='position_2',
            field=models.CharField(blank=True, db_comment='着順_2', help_text='着順_2', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='horsedata',
            name='position_3',
            field=models.CharField(blank=True, db_comment='着順_3', help_text='着順_3', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='horsedata',
            name='position_4',
            field=models.CharField(blank=True, db_comment='着順_4', help_text='着順_4', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='horsedata',
            name='position_5',
            field=models.CharField(blank=True, db_comment='着順_5', help_text='着順_5', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='horsedata',
            name='position_6',
            field=models.CharField(blank=True, db_comment='着順_6', help_text='着順_6', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='horsedata',
            name='position_7',
            field=models.CharField(blank=True, db_comment='着順_7', help_text='着順_7', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='horsedata',
            name='position_8',
            field=models.CharField(blank=True, db_comment='着順_8', help_text='着順_8', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='horsedata',
            name='position_9',
            field=models.CharField(blank=True, db_comment='着順_9', help_text='着順_9', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='horsedata',
            name='prize_1',
            field=models.CharField(blank=True, db_comment='賞金_1', help_text='賞金_1', null=True),
        ),
        migrations.AddField(
            model_name='horsedata',
            name='prize_10',
            field=models.CharField(blank=True, db_comment='賞金_10', help_text='賞金_10', null=True),
        ),
        migrations.AddField(
            model_name='horsedata',
            name='prize_2',
            field=models.CharField(blank=True, db_comment='賞金_2', help_text='賞金_2', null=True),
        ),
        migrations.AddField(
            model_name='horsedata',
            name='prize_3',
            field=models.CharField(blank=True, db_comment='賞金_3', help_text='賞金_3', null=True),
        ),
        migrations.AddField(
            model_name='horsedata',
            name='prize_4',
            field=models.CharField(blank=True, db_comment='賞金_4', help_text='賞金_4', null=True),
        ),
        migrations.AddField(
            model_name='horsedata',
            name='prize_5',
            field=models.CharField(blank=True, db_comment='賞金_5', help_text='賞金_5', null=True),
        ),
        migrations.AddField(
            model_name='horsedata',
            name='prize_6',
            field=models.CharField(blank=True, db_comment='賞金_6', help_text='賞金_6', null=True),
        ),
        migrations.AddField(
            model_name='horsedata',
            name='prize_7',
            field=models.CharField(blank=True, db_comment='賞金_7', help_text='賞金_7', null=True),
        ),
        migrations.AddField(
            model_name='horsedata',
            name='prize_8',
            field=models.CharField(blank=True, db_comment='賞金_8', help_text='賞金_8', null=True),
        ),
        migrations.AddField(
            model_name='horsedata',
            name='prize_9',
            field=models.CharField(blank=True, db_comment='賞金_9', help_text='賞金_9', null=True),
        ),
        migrations.AddField(
            model_name='horsedata',
            name='race_date_1',
            field=models.CharField(blank=True, db_comment='レース日付_1', help_text='レース日付_1', null=True),
        ),
        migrations.AddField(
            model_name='horsedata',
            name='race_date_10',
            field=models.CharField(blank=True, db_comment='レース日付_10', help_text='レース日付_10', null=True),
        ),
        migrations.AddField(
            model_name='horsedata',
            name='race_date_2',
            field=models.CharField(blank=True, db_comment='レース日付_2', help_text='レース日付_2', null=True),
        ),
        migrations.AddField(
            model_name='horsedata',
            name='race_date_3',
            field=models.CharField(blank=True, db_comment='レース日付_3', help_text='レース日付_3', null=True),
        ),
        migrations.AddField(
            model_name='horsedata',
            name='race_date_4',
            field=models.CharField(blank=True, db_comment='レース日付_4', help_text='レース日付_4', null=True),
        ),
        migrations.AddField(
            model_name='horsedata',
            name='race_date_5',
            field=models.CharField(blank=True, db_comment='レース日付_5', help_text='レース日付_5', null=True),
        ),
        migrations.AddField(
            model_name='horsedata',
            name='race_date_6',
            field=models.CharField(blank=True, db_comment='レース日付_6', help_text='レース日付_6', null=True),
        ),
        migrations.AddField(
            model_name='horsedata',
            name='race_date_7',
            field=models.CharField(blank=True, db_comment='レース日付_7', help_text='レース日付_7', null=True),
        ),
        migrations.AddField(
            model_name='horsedata',
            name='race_date_8',
            field=models.CharField(blank=True, db_comment='レース日付_8', help_text='レース日付_8', null=True),
        ),
        migrations.AddField(
            model_name='horsedata',
            name='race_date_9',
            field=models.CharField(blank=True, db_comment='レース日付_9', help_text='レース日付_9', null=True),
        ),
        migrations.AddField(
            model_name='horsedata',
            name='race_name_1',
            field=models.CharField(blank=True, db_comment='レース名_1', help_text='レース名_1', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='horsedata',
            name='race_name_10',
            field=models.CharField(blank=True, db_comment='レース名_10', help_text='レース名_10', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='horsedata',
            name='race_name_2',
            field=models.CharField(blank=True, db_comment='レース名_2', help_text='レース名_2', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='horsedata',
            name='race_name_3',
            field=models.CharField(blank=True, db_comment='レース名_3', help_text='レース名_3', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='horsedata',
            name='race_name_4',
            field=models.CharField(blank=True, db_comment='レース名_4', help_text='レース名_4', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='horsedata',
            name='race_name_5',
            field=models.CharField(blank=True, db_comment='レース名_5', help_text='レース名_5', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='horsedata',
            name='race_name_6',
            field=models.CharField(blank=True, db_comment='レース名_6', help_text='レース名_6', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='horsedata',
            name='race_name_7',
            field=models.CharField(blank=True, db_comment='レース名_7', help_text='レース名_7', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='horsedata',
            name='race_name_8',
            field=models.CharField(blank=True, db_comment='レース名_8', help_text='レース名_8', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='horsedata',
            name='race_name_9',
            field=models.CharField(blank=True, db_comment='レース名_9', help_text='レース名_9', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='horsedata',
            name='race_place_1',
            field=models.CharField(blank=True, db_comment='開催場所_1', help_text='開催場所_1', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='horsedata',
            name='race_place_10',
            field=models.CharField(blank=True, db_comment='開催場所_10', help_text='開催場所_10', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='horsedata',
            name='race_place_2',
            field=models.CharField(blank=True, db_comment='開催場所_2', help_text='開催場所_2', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='horsedata',
            name='race_place_3',
            field=models.CharField(blank=True, db_comment='開催場所_3', help_text='開催場所_3', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='horsedata',
            name='race_place_4',
            field=models.CharField(blank=True, db_comment='開催場所_4', help_text='開催場所_4', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='horsedata',
            name='race_place_5',
            field=models.CharField(blank=True, db_comment='開催場所_5', help_text='開催場所_5', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='horsedata',
            name='race_place_6',
            field=models.CharField(blank=True, db_comment='開催場所_6', help_text='開催場所_6', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='horsedata',
            name='race_place_7',
            field=models.CharField(blank=True, db_comment='開催場所_7', help_text='開催場所_7', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='horsedata',
            name='race_place_8',
            field=models.CharField(blank=True, db_comment='開催場所_8', help_text='開催場所_8', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='horsedata',
            name='race_place_9',
            field=models.CharField(blank=True, db_comment='開催場所_9', help_text='開催場所_9', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='horsedata',
            name='rank_1',
            field=models.CharField(blank=True, db_comment='順位_1', help_text='順位_1', max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='horsedata',
            name='rank_10',
            field=models.CharField(blank=True, db_comment='順位_10', help_text='順位_10', max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='horsedata',
            name='rank_2',
            field=models.CharField(blank=True, db_comment='順位_2', help_text='順位_2', max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='horsedata',
            name='rank_3',
            field=models.CharField(blank=True, db_comment='順位_3', help_text='順位_3', max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='horsedata',
            name='rank_4',
            field=models.CharField(blank=True, db_comment='順位_4', help_text='順位_4', max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='horsedata',
            name='rank_5',
            field=models.CharField(blank=True, db_comment='順位_5', help_text='順位_5', max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='horsedata',
            name='rank_6',
            field=models.CharField(blank=True, db_comment='順位_6', help_text='順位_6', max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='horsedata',
            name='rank_7',
            field=models.CharField(blank=True, db_comment='順位_7', help_text='順位_7', max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='horsedata',
            name='rank_8',
            field=models.CharField(blank=True, db_comment='順位_8', help_text='順位_8', max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='horsedata',
            name='rank_9',
            field=models.CharField(blank=True, db_comment='順位_9', help_text='順位_9', max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='horsedata',
            name='time_1',
            field=models.CharField(blank=True, db_comment='タイム_1', help_text='タイム_1', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='horsedata',
            name='time_10',
            field=models.CharField(blank=True, db_comment='タイム_10', help_text='タイム_10', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='horsedata',
            name='time_2',
            field=models.CharField(blank=True, db_comment='タイム_2', help_text='タイム_2', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='horsedata',
            name='time_3',
            field=models.CharField(blank=True, db_comment='タイム_3', help_text='タイム_3', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='horsedata',
            name='time_4',
            field=models.CharField(blank=True, db_comment='タイム_4', help_text='タイム_4', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='horsedata',
            name='time_5',
            field=models.CharField(blank=True, db_comment='タイム_5', help_text='タイム_5', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='horsedata',
            name='time_6',
            field=models.CharField(blank=True, db_comment='タイム_6', help_text='タイム_6', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='horsedata',
            name='time_7',
            field=models.CharField(blank=True, db_comment='タイム_7', help_text='タイム_7', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='horsedata',
            name='time_8',
            field=models.CharField(blank=True, db_comment='タイム_8', help_text='タイム_8', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='horsedata',
            name='time_9',
            field=models.CharField(blank=True, db_comment='タイム_9', help_text='タイム_9', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='horsedata',
            name='time_diff_1',
            field=models.CharField(blank=True, db_comment='タイム差_1', help_text='タイム差_1', null=True),
        ),
        migrations.AddField(
            model_name='horsedata',
            name='time_diff_10',
            field=models.CharField(blank=True, db_comment='タイム差_10', help_text='タイム差_10', null=True),
        ),
        migrations.AddField(
            model_name='horsedata',
            name='time_diff_2',
            field=models.CharField(blank=True, db_comment='タイム差_2', help_text='タイム差_2', null=True),
        ),
        migrations.AddField(
            model_name='horsedata',
            name='time_diff_3',
            field=models.CharField(blank=True, db_comment='タイム差_3', help_text='タイム差_3', null=True),
        ),
        migrations.AddField(
            model_name='horsedata',
            name='time_diff_4',
            field=models.CharField(blank=True, db_comment='タイム差_4', help_text='タイム差_4', null=True),
        ),
        migrations.AddField(
            model_name='horsedata',
            name='time_diff_5',
            field=models.CharField(blank=True, db_comment='タイム差_5', help_text='タイム差_5', null=True),
        ),
        migrations.AddField(
            model_name='horsedata',
            name='time_diff_6',
            field=models.CharField(blank=True, db_comment='タイム差_6', help_text='タイム差_6', null=True),
        ),
        migrations.AddField(
            model_name='horsedata',
            name='time_diff_7',
            field=models.CharField(blank=True, db_comment='タイム差_7', help_text='タイム差_7', null=True),
        ),
        migrations.AddField(
            model_name='horsedata',
            name='time_diff_8',
            field=models.CharField(blank=True, db_comment='タイム差_8', help_text='タイム差_8', null=True),
        ),
        migrations.AddField(
            model_name='horsedata',
            name='time_diff_9',
            field=models.CharField(blank=True, db_comment='タイム差_9', help_text='タイム差_9', null=True),
        ),
        migrations.AddField(
            model_name='horsedata',
            name='track_condition_1',
            field=models.CharField(blank=True, db_comment='コース状態_1', help_text='コース状態_1', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='horsedata',
            name='track_condition_10',
            field=models.CharField(blank=True, db_comment='コース状態_10', help_text='コース状態_10', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='horsedata',
            name='track_condition_2',
            field=models.CharField(blank=True, db_comment='コース状態_2', help_text='コース状態_2', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='horsedata',
            name='track_condition_3',
            field=models.CharField(blank=True, db_comment='コース状態_3', help_text='コース状態_3', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='horsedata',
            name='track_condition_4',
            field=models.CharField(blank=True, db_comment='コース状態_4', help_text='コース状態_4', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='horsedata',
            name='track_condition_5',
            field=models.CharField(blank=True, db_comment='コース状態_5', help_text='コース状態_5', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='horsedata',
            name='track_condition_6',
            field=models.CharField(blank=True, db_comment='コース状態_6', help_text='コース状態_6', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='horsedata',
            name='track_condition_7',
            field=models.CharField(blank=True, db_comment='コース状態_7', help_text='コース状態_7', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='horsedata',
            name='track_condition_8',
            field=models.CharField(blank=True, db_comment='コース状態_8', help_text='コース状態_8', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='horsedata',
            name='track_condition_9',
            field=models.CharField(blank=True, db_comment='コース状態_9', help_text='コース状態_9', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='horsedata',
            name='weather_1',
            field=models.CharField(blank=True, db_comment='天候_1', help_text='天候_1', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='horsedata',
            name='weather_10',
            field=models.CharField(blank=True, db_comment='天候_10', help_text='天候_10', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='horsedata',
            name='weather_2',
            field=models.CharField(blank=True, db_comment='天候_2', help_text='天候_2', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='horsedata',
            name='weather_3',
            field=models.CharField(blank=True, db_comment='天候_3', help_text='天候_3', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='horsedata',
            name='weather_4',
            field=models.CharField(blank=True, db_comment='天候_4', help_text='天候_4', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='horsedata',
            name='weather_5',
            field=models.CharField(blank=True, db_comment='天候_5', help_text='天候_5', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='horsedata',
            name='weather_6',
            field=models.CharField(blank=True, db_comment='天候_6', help_text='天候_6', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='horsedata',
            name='weather_7',
            field=models.CharField(blank=True, db_comment='天候_7', help_text='天候_7', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='horsedata',
            name='weather_8',
            field=models.CharField(blank=True, db_comment='天候_8', help_text='天候_8', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='horsedata',
            name='weather_9',
            field=models.CharField(blank=True, db_comment='天候_9', help_text='天候_9', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='horsedata',
            name='weight_1',
            field=models.CharField(blank=True, db_comment='体重_1', help_text='体重_1', null=True),
        ),
        migrations.AddField(
            model_name='horsedata',
            name='weight_10',
            field=models.CharField(blank=True, db_comment='体重_10', help_text='体重_10', null=True),
        ),
        migrations.AddField(
            model_name='horsedata',
            name='weight_2',
            field=models.CharField(blank=True, db_comment='体重_2', help_text='体重_2', null=True),
        ),
        migrations.AddField(
            model_name='horsedata',
            name='weight_3',
            field=models.CharField(blank=True, db_comment='体重_3', help_text='体重_3', null=True),
        ),
        migrations.AddField(
            model_name='horsedata',
            name='weight_4',
            field=models.CharField(blank=True, db_comment='体重_4', help_text='体重_4', null=True),
        ),
        migrations.AddField(
            model_name='horsedata',
            name='weight_5',
            field=models.CharField(blank=True, db_comment='体重_5', help_text='体重_5', null=True),
        ),
        migrations.AddField(
            model_name='horsedata',
            name='weight_6',
            field=models.CharField(blank=True, db_comment='体重_6', help_text='体重_6', null=True),
        ),
        migrations.AddField(
            model_name='horsedata',
            name='weight_7',
            field=models.CharField(blank=True, db_comment='体重_7', help_text='体重_7', null=True),
        ),
        migrations.AddField(
            model_name='horsedata',
            name='weight_8',
            field=models.CharField(blank=True, db_comment='体重_8', help_text='体重_8', null=True),
        ),
        migrations.AddField(
            model_name='horsedata',
            name='weight_9',
            field=models.CharField(blank=True, db_comment='体重_9', help_text='体重_9', null=True),
        ),
        migrations.AddField(
            model_name='horsedata',
            name='win_1_flg_1',
            field=models.BooleanField(db_comment='1着フラグ_1', default=False, help_text='1着フラグ_1'),
        ),
        migrations.AddField(
            model_name='horsedata',
            name='win_1_flg_10',
            field=models.BooleanField(db_comment='1着フラグ_10', default=False, help_text='1着フラグ_10'),
        ),
        migrations.AddField(
            model_name='horsedata',
            name='win_1_flg_2',
            field=models.BooleanField(db_comment='1着フラグ_2', default=False, help_text='1着フラグ_2'),
        ),
        migrations.AddField(
            model_name='horsedata',
            name='win_1_flg_3',
            field=models.BooleanField(db_comment='1着フラグ_3', default=False, help_text='1着フラグ_3'),
        ),
        migrations.AddField(
            model_name='horsedata',
            name='win_1_flg_4',
            field=models.BooleanField(db_comment='1着フラグ_4', default=False, help_text='1着フラグ_4'),
        ),
        migrations.AddField(
            model_name='horsedata',
            name='win_1_flg_5',
            field=models.BooleanField(db_comment='1着フラグ_5', default=False, help_text='1着フラグ_5'),
        ),
        migrations.AddField(
            model_name='horsedata',
            name='win_1_flg_6',
            field=models.BooleanField(db_comment='1着フラグ_6', default=False, help_text='1着フラグ_6'),
        ),
        migrations.AddField(
            model_name='horsedata',
            name='win_1_flg_7',
            field=models.BooleanField(db_comment='1着フラグ_7', default=False, help_text='1着フラグ_7'),
        ),
        migrations.AddField(
            model_name='horsedata',
            name='win_1_flg_8',
            field=models.BooleanField(db_comment='1着フラグ_8', default=False, help_text='1着フラグ_8'),
        ),
        migrations.AddField(
            model_name='horsedata',
            name='win_1_flg_9',
            field=models.BooleanField(db_comment='1着フラグ_9', default=False, help_text='1着フラグ_9'),
        ),
        migrations.AddField(
            model_name='horsedata',
            name='win_2_flg_1',
            field=models.BooleanField(db_comment='2着フラグ_1', default=False, help_text='2着フラグ_1'),
        ),
        migrations.AddField(
            model_name='horsedata',
            name='win_2_flg_10',
            field=models.BooleanField(db_comment='2着フラグ_10', default=False, help_text='2着フラグ_10'),
        ),
        migrations.AddField(
            model_name='horsedata',
            name='win_2_flg_2',
            field=models.BooleanField(db_comment='2着フラグ_2', default=False, help_text='2着フラグ_2'),
        ),
        migrations.AddField(
            model_name='horsedata',
            name='win_2_flg_3',
            field=models.BooleanField(db_comment='2着フラグ_3', default=False, help_text='2着フラグ_3'),
        ),
        migrations.AddField(
            model_name='horsedata',
            name='win_2_flg_4',
            field=models.BooleanField(db_comment='2着フラグ_4', default=False, help_text='2着フラグ_4'),
        ),
        migrations.AddField(
            model_name='horsedata',
            name='win_2_flg_5',
            field=models.BooleanField(db_comment='2着フラグ_5', default=False, help_text='2着フラグ_5'),
        ),
        migrations.AddField(
            model_name='horsedata',
            name='win_2_flg_6',
            field=models.BooleanField(db_comment='2着フラグ_6', default=False, help_text='2着フラグ_6'),
        ),
        migrations.AddField(
            model_name='horsedata',
            name='win_2_flg_7',
            field=models.BooleanField(db_comment='2着フラグ_7', default=False, help_text='2着フラグ_7'),
        ),
        migrations.AddField(
            model_name='horsedata',
            name='win_2_flg_8',
            field=models.BooleanField(db_comment='2着フラグ_8', default=False, help_text='2着フラグ_8'),
        ),
        migrations.AddField(
            model_name='horsedata',
            name='win_2_flg_9',
            field=models.BooleanField(db_comment='2着フラグ_9', default=False, help_text='2着フラグ_9'),
        ),
        migrations.AddField(
            model_name='horsedata',
            name='win_3_flg_1',
            field=models.BooleanField(db_comment='3着フラグ_1', default=False, help_text='3着フラグ_1'),
        ),
        migrations.AddField(
            model_name='horsedata',
            name='win_3_flg_10',
            field=models.BooleanField(db_comment='3着フラグ_10', default=False, help_text='3着フラグ_10'),
        ),
        migrations.AddField(
            model_name='horsedata',
            name='win_3_flg_2',
            field=models.BooleanField(db_comment='3着フラグ_2', default=False, help_text='3着フラグ_2'),
        ),
        migrations.AddField(
            model_name='horsedata',
            name='win_3_flg_3',
            field=models.BooleanField(db_comment='3着フラグ_3', default=False, help_text='3着フラグ_3'),
        ),
        migrations.AddField(
            model_name='horsedata',
            name='win_3_flg_4',
            field=models.BooleanField(db_comment='3着フラグ_4', default=False, help_text='3着フラグ_4'),
        ),
        migrations.AddField(
            model_name='horsedata',
            name='win_3_flg_5',
            field=models.BooleanField(db_comment='3着フラグ_5', default=False, help_text='3着フラグ_5'),
        ),
        migrations.AddField(
            model_name='horsedata',
            name='win_3_flg_6',
            field=models.BooleanField(db_comment='3着フラグ_6', default=False, help_text='3着フラグ_6'),
        ),
        migrations.AddField(
            model_name='horsedata',
            name='win_3_flg_7',
            field=models.BooleanField(db_comment='3着フラグ_7', default=False, help_text='3着フラグ_7'),
        ),
        migrations.AddField(
            model_name='horsedata',
            name='win_3_flg_8',
            field=models.BooleanField(db_comment='3着フラグ_8', default=False, help_text='3着フラグ_8'),
        ),
        migrations.AddField(
            model_name='horsedata',
            name='win_3_flg_9',
            field=models.BooleanField(db_comment='3着フラグ_9', default=False, help_text='3着フラグ_9'),
        ),
        migrations.AddField(
            model_name='horsedata',
            name='winner_1',
            field=models.CharField(blank=True, db_comment='優勝馬_1', help_text='優勝馬_1', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='horsedata',
            name='winner_10',
            field=models.CharField(blank=True, db_comment='優勝馬_10', help_text='優勝馬_10', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='horsedata',
            name='winner_2',
            field=models.CharField(blank=True, db_comment='優勝馬_2', help_text='優勝馬_2', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='horsedata',
            name='winner_3',
            field=models.CharField(blank=True, db_comment='優勝馬_3', help_text='優勝馬_3', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='horsedata',
            name='winner_4',
            field=models.CharField(blank=True, db_comment='優勝馬_4', help_text='優勝馬_4', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='horsedata',
            name='winner_5',
            field=models.CharField(blank=True, db_comment='優勝馬_5', help_text='優勝馬_5', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='horsedata',
            name='winner_6',
            field=models.CharField(blank=True, db_comment='優勝馬_6', help_text='優勝馬_6', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='horsedata',
            name='winner_7',
            field=models.CharField(blank=True, db_comment='優勝馬_7', help_text='優勝馬_7', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='horsedata',
            name='winner_8',
            field=models.CharField(blank=True, db_comment='優勝馬_8', help_text='優勝馬_8', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='horsedata',
            name='winner_9',
            field=models.CharField(blank=True, db_comment='優勝馬_9', help_text='優勝馬_9', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='basedata',
            name='race_date',
            field=models.DateField(blank=True, db_comment='レース日付', help_text='レース日付', null=True),
        ),
        migrations.AlterField(
            model_name='resultdata',
            name='race_date',
            field=models.DateField(blank=True, db_comment='レース日付', help_text='レース日付', null=True),
        ),
        migrations.AlterModelTable(
            name='compareview',
            table='v_compare_base_result',
        ),
    ]
