# Generated by Django 5.1.4 on 2025-01-13 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_folder', '0002_missingraceids_remove_horsedata_unique_horse_info_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeekEnd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('race_date', models.DateField(db_comment='レース日付', help_text='レース日付')),
            ],
            options={
                'db_table': 'v_weekend',
                'managed': False,
            },
        ),
    ]
