# Generated by Django 5.1.4 on 2025-02-11 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_folder', '0004_comparehorseview_createraceidsview_newhorseurlview_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='horsedata',
            name='g1_flg_1',
        ),
        migrations.RemoveField(
            model_name='horsedata',
            name='g2_flg_1',
        ),
        migrations.RemoveField(
            model_name='horsedata',
            name='g3_flg_1',
        ),
        migrations.RemoveField(
            model_name='horsedata',
            name='l_flg_1',
        ),
        migrations.RemoveField(
            model_name='horsedata',
            name='not_win_flg_1',
        ),
        migrations.RemoveField(
            model_name='horsedata',
            name='op_flg_1',
        ),
        migrations.RemoveField(
            model_name='horsedata',
            name='race_id',
        ),
        migrations.RemoveField(
            model_name='horsedata',
            name='win_1_flg_1',
        ),
        migrations.RemoveField(
            model_name='horsedata',
            name='win_2_flg_1',
        ),
        migrations.RemoveField(
            model_name='horsedata',
            name='win_3_flg_1',
        ),
        migrations.AddField(
            model_name='horsedata',
            name='g1_flg',
            field=models.BooleanField(db_comment='G1フラグ', default=False, help_text='G1フラグ'),
        ),
        migrations.AddField(
            model_name='horsedata',
            name='g2_flg',
            field=models.BooleanField(db_comment='G2フラグ', default=False, help_text='G2フラグ'),
        ),
        migrations.AddField(
            model_name='horsedata',
            name='g3_flg',
            field=models.BooleanField(db_comment='G3フラグ', default=False, help_text='G3フラグ'),
        ),
        migrations.AddField(
            model_name='horsedata',
            name='l_flg',
            field=models.BooleanField(db_comment='lフラグ', default=False, help_text='lフラグ'),
        ),
        migrations.AddField(
            model_name='horsedata',
            name='not_win_flg',
            field=models.BooleanField(db_comment='未勝利フラグ', default=False, help_text='未勝利フラグ'),
        ),
        migrations.AddField(
            model_name='horsedata',
            name='op_flg',
            field=models.BooleanField(db_comment='opフラグ', default=False, help_text='opフラグ'),
        ),
        migrations.AddField(
            model_name='horsedata',
            name='win_1_flg',
            field=models.BooleanField(db_comment='1着フラグ', default=False, help_text='1着フラグ'),
        ),
        migrations.AddField(
            model_name='horsedata',
            name='win_2_flg',
            field=models.BooleanField(db_comment='2着フラグ', default=False, help_text='2着フラグ'),
        ),
        migrations.AddField(
            model_name='horsedata',
            name='win_3_flg',
            field=models.BooleanField(db_comment='3着フラグ', default=False, help_text='3着フラグ'),
        ),
        migrations.AlterField(
            model_name='horsedata',
            name='new_flg',
            field=models.BooleanField(db_comment='新馬戦フラグ', default=False, help_text='新馬戦フラグ'),
        ),
    ]
