# Generated by Django 5.1.4 on 2025-02-15 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_folder', '0005_remove_horsedata_g1_flg_1_remove_horsedata_g2_flg_1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompareBaseHorseView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('race_date', models.DateField(db_comment='レース日付', help_text='レース日付')),
                ('horse_name', models.CharField(db_comment='馬名', help_text='馬名')),
                ('horse_url', models.CharField(db_comment='馬URL', help_text='馬URL')),
            ],
            options={
                'db_table': 'v_compare_base_horse',
                'managed': False,
            },
        ),
    ]
