# Generated by Django 5.1.4 on 2025-02-15 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_folder', '0006_comparebasehorseview'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompareBaseJockeyView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('race_date', models.DateField(db_comment='レース日付', help_text='レース日付')),
                ('jockey_name', models.CharField(db_comment='騎手名', help_text='騎手名')),
                ('jockey_url', models.CharField(db_comment='騎手URL', help_text='騎手URL')),
            ],
            options={
                'db_table': 'v_compare_base_jockey',
                'managed': False,
            },
        ),
    ]
