# Generated by Django 5.1.4 on 2025-02-16 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_folder', '0007_comparebasejockeyview'),
    ]

    operations = [
        migrations.CreateModel(
            name='JockeyData',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('jockey_id', models.CharField(db_comment='騎手ID', help_text='騎手ID', max_length=20)),
                ('jockey_name', models.CharField(db_comment='騎手名', help_text='騎手名', max_length=255)),
                ('race_date', models.CharField(blank=True, db_comment='レース日付', help_text='レース日付', null=True)),
                ('race_place', models.CharField(blank=True, db_comment='開催場所', help_text='開催場所', max_length=255, null=True)),
                ('weather', models.CharField(blank=True, db_comment='天候', help_text='天候', max_length=50, null=True)),
                ('race_name', models.CharField(blank=True, db_comment='レース名', help_text='レース名', max_length=255, null=True)),
                ('count', models.CharField(blank=True, db_comment='頭数', help_text='頭数', max_length=5, null=True)),
                ('frame', models.CharField(blank=True, db_comment='枠番号', help_text='枠番号', max_length=5, null=True)),
                ('horse_number', models.CharField(blank=True, db_comment='馬番', help_text='馬番', max_length=5, null=True)),
                ('odds', models.CharField(blank=True, db_comment='オッズ', help_text='オッズ', null=True)),
                ('popularity', models.CharField(blank=True, db_comment='人気順', help_text='人気順', max_length=5, null=True)),
                ('rank', models.CharField(blank=True, db_comment='順位', help_text='順位', max_length=5, null=True)),
                ('horse', models.CharField(blank=True, db_comment='馬名', help_text='馬名', max_length=255, null=True)),
                ('weight', models.CharField(blank=True, db_comment='斤量', help_text='斤量', null=True)),
                ('distance', models.CharField(blank=True, db_comment='距離', help_text='距離', null=True)),
                ('track_condition', models.CharField(blank=True, db_comment='コース状態', help_text='コース状態', max_length=50, null=True)),
                ('time', models.CharField(blank=True, db_comment='タイム', help_text='タイム', max_length=20, null=True)),
                ('time_diff', models.CharField(blank=True, db_comment='着差', help_text='着差', null=True)),
                ('position', models.CharField(blank=True, db_comment='通過', help_text='通過', max_length=20, null=True)),
                ('pace', models.CharField(blank=True, db_comment='ペース', help_text='ペース', max_length=20, null=True)),
                ('up', models.CharField(blank=True, db_comment='上り', help_text='上り', null=True)),
                ('body_weight', models.CharField(blank=True, db_comment='体重', help_text='体重', max_length=10, null=True)),
                ('winner', models.CharField(blank=True, db_comment='勝ち馬', help_text='勝ち馬', max_length=255, null=True)),
                ('prize', models.CharField(blank=True, db_comment='賞金', help_text='賞金', null=True)),
                ('new_flg', models.BooleanField(db_comment='新馬戦フラグ', default=False, help_text='新馬戦フラグ')),
                ('win_1_flg', models.BooleanField(db_comment='1着フラグ', default=False, help_text='1着フラグ')),
                ('win_2_flg', models.BooleanField(db_comment='2着フラグ', default=False, help_text='2着フラグ')),
                ('win_3_flg', models.BooleanField(db_comment='3着フラグ', default=False, help_text='3着フラグ')),
                ('not_win_flg', models.BooleanField(db_comment='未勝利フラグ', default=False, help_text='未勝利フラグ')),
                ('g3_flg', models.BooleanField(db_comment='G3フラグ', default=False, help_text='G3フラグ')),
                ('g2_flg', models.BooleanField(db_comment='G2フラグ', default=False, help_text='G2フラグ')),
                ('g1_flg', models.BooleanField(db_comment='G1フラグ', default=False, help_text='G1フラグ')),
                ('l_flg', models.BooleanField(db_comment='lフラグ', default=False, help_text='lフラグ')),
                ('op_flg', models.BooleanField(db_comment='opフラグ', default=False, help_text='opフラグ')),
                ('created_at', models.DateTimeField(db_comment='作成日時', help_text='作成日時')),
                ('updated_at', models.DateTimeField(db_comment='更新日時', help_text='更新日時')),
                ('created_user', models.CharField(db_comment='作成ユーザーID', help_text='作成ユーザーID', max_length=255, null=True)),
                ('updated_user', models.CharField(db_comment='更新ユーザーID', help_text='更新ユーザーID', max_length=255, null=True)),
            ],
            options={
                'db_table': 't_jockey_info',
            },
        ),
        migrations.RemoveField(
            model_name='horsedata',
            name='finish',
        ),
        migrations.AddField(
            model_name='horsedata',
            name='up',
            field=models.CharField(blank=True, db_comment='上り', help_text='上り', null=True),
        ),
        migrations.AlterField(
            model_name='horsedata',
            name='body_weight',
            field=models.CharField(blank=True, db_comment='体重', help_text='体重', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='horsedata',
            name='position',
            field=models.CharField(blank=True, db_comment='通過', help_text='通過', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='horsedata',
            name='time_diff',
            field=models.CharField(blank=True, db_comment='着差', help_text='着差', null=True),
        ),
        migrations.AlterField(
            model_name='horsedata',
            name='weight',
            field=models.CharField(blank=True, db_comment='斤量', help_text='斤量', null=True),
        ),
        migrations.AlterField(
            model_name='horsedata',
            name='winner',
            field=models.CharField(blank=True, db_comment='勝ち馬', help_text='勝ち馬', max_length=255, null=True),
        ),
    ]
