# Generated by Django 5.1.4 on 2025-03-03 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_folder', '0008_jockeydata_remove_horsedata_finish_horsedata_up_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jockeydata',
            name='race',
            field=models.CharField(blank=True, db_comment='レース目', help_text='レース目', max_length=2, null=True),
        ),
    ]
