# Generated by Django 5.1.4 on 2025-03-06 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_folder', '0010_alter_jockeydata_race'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jockeydata',
            name='race',
            field=models.CharField(blank=True, db_comment='レース目', help_text='レース目', null=True),
        ),
    ]
