# Generated by Django 5.1.4 on 2025-04-07 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_folder', '0011_alter_jockeydata_race'),
    ]

    operations = [
        migrations.AddField(
            model_name='basedata',
            name='distance',
            field=models.CharField(db_comment='距離', help_text='距離', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='basedata',
            name='track_condition',
            field=models.CharField(db_comment='馬場', help_text='馬場', null=True),
        ),
        migrations.AddField(
            model_name='basedata',
            name='weather',
            field=models.CharField(db_comment='天気', help_text='天気', null=True),
        ),
    ]
