# Generated by Django 5.1.4 on 2025-04-09 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_folder', '0013_finalhorsedata_finaljockeydata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finalhorsedata',
            name='field',
            field=models.CharField(db_column='FIELD', db_comment='フィールド', help_text='フィールド', max_length=5),
        ),
    ]
