# Generated by Django 5.1.4 on 2025-04-10 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_folder', '0015_alter_finaljockeydata_field'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinalBaseInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('race_id', models.CharField(db_column='RACE_ID', help_text='レースID', max_length=12)),
                ('today_race_date', models.DateField(db_column='TODAY_RACE_DATE', help_text='当日レース日付')),
                ('today_race_no', models.SmallIntegerField(db_column='TODAY_RACE_NO', help_text='当日レース番号')),
                ('place_id', models.SmallIntegerField(blank=True, db_column='PLACE_ID', help_text='開催地ID', null=True)),
                ('place_name', models.CharField(blank=True, db_column='PLACE_NAME', help_text='開催地名', max_length=10, null=True)),
                ('horse_id', models.CharField(blank=True, db_column='HORSE_ID', help_text='馬ID', max_length=10, null=True)),
                ('horse', models.CharField(blank=True, db_column='HORSE', help_text='馬名', max_length=20, null=True)),
                ('frame_number', models.SmallIntegerField(blank=True, db_column='FRAME_NUMBER', help_text='枠番', null=True)),
                ('horse_number', models.SmallIntegerField(blank=True, db_column='HORSE_NUMBER', help_text='馬番', null=True)),
                ('sex', models.CharField(blank=True, db_column='SEX', help_text='性別', max_length=5, null=True)),
                ('age', models.SmallIntegerField(blank=True, db_column='AGE', help_text='年齢', null=True)),
                ('weight', models.SmallIntegerField(blank=True, db_column='WEIGHT', help_text='斤量', null=True)),
                ('body_weight', models.SmallIntegerField(blank=True, db_column='BODY_WEIGHT', help_text='馬体重', null=True)),
                ('jockey_id', models.CharField(blank=True, db_column='JOCKEY_ID', help_text='騎手ID', max_length=5, null=True)),
                ('jockey', models.CharField(blank=True, db_column='JOCKEY', help_text='騎手名', max_length=20, null=True)),
                ('weight_4kg_cut_flg', models.BooleanField(db_column='WEIGHT_4KG_CUT_FLG', default=False)),
                ('weight_3kg_cut_flg', models.BooleanField(db_column='WEIGHT_3KG_CUT_FLG', default=False)),
                ('weight_2kg_cut_flg', models.BooleanField(db_column='WEIGHT_2KG_CUT_FLG', default=False)),
                ('weight_1kg_cut_flg', models.BooleanField(db_column='WEIGHT_1KG_CUT_FLG', default=False)),
                ('women_weight_2kg_cut_flg', models.BooleanField(db_column='WOMEN_WEIGHT_2KG_CUT_FLG', default=False)),
                ('stable_name', models.CharField(blank=True, db_column='STABLE_NAME', help_text='厩舎名', max_length=20, null=True)),
                ('odds', models.FloatField(blank=True, db_column='ODDS', help_text='オッズ', null=True)),
                ('popularity', models.SmallIntegerField(blank=True, db_column='POPULARITY', help_text='人気順', null=True)),
                ('new_flg', models.BooleanField(db_column='NEW_FLG', default=False)),
                ('g1_flg', models.BooleanField(db_column='G1_FLG', default=False)),
                ('g2_flg', models.BooleanField(db_column='G2_FLG', default=False)),
                ('g3_flg', models.BooleanField(db_column='G3_FLG', default=False)),
                ('l_flg', models.BooleanField(db_column='L_FLG', default=False)),
                ('not_win_flg', models.BooleanField(db_column='NOT_WIN_FLG', default=False)),
                ('op_flg', models.BooleanField(db_column='OP_FLG', default=False)),
                ('win_1_flg', models.BooleanField(db_column='WIN_1_FLG', default=False)),
                ('win_2_flg', models.BooleanField(db_column='WIN_2_FLG', default=False)),
                ('win_3_flg', models.BooleanField(db_column='WIN_3_FLG', default=False)),
                ('is_win5', models.BooleanField(db_column='IS_WIN5', default=False)),
            ],
            options={
                'verbose_name': '最終ベース情報',
                'verbose_name_plural': '最終ベース情報一覧',
                'db_table': 't_final_base_info',
            },
        ),
        migrations.CreateModel(
            name='FinalResultInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('race_id', models.CharField(db_column='RACE_ID', help_text='レースID', max_length=12)),
                ('rank', models.SmallIntegerField(db_column='RANK', help_text='着順')),
                ('race_time', models.FloatField(blank=True, db_column='RACE_TIME', help_text='レースタイム', null=True)),
                ('corner_order', models.CharField(blank=True, db_column='CORNER_ORDER', help_text='コーナー順', max_length=10, null=True)),
                ('positions', models.CharField(blank=True, db_column='POSITIONS', help_text='走行位置', max_length=10, null=True)),
                ('positions_tie', models.CharField(blank=True, db_column='POSITIONS_TIE', help_text='同着位置', max_length=10, null=True)),
                ('pay1', models.IntegerField(blank=True, db_column='PAY1', help_text='単勝払戻', null=True)),
                ('pay1_tie', models.IntegerField(blank=True, db_column='PAY1_TIE', help_text='単勝同着払戻', null=True)),
                ('pay123_1', models.IntegerField(blank=True, db_column='PAY123_1', help_text='3連単 1番目', null=True)),
                ('pay123_2', models.IntegerField(blank=True, db_column='PAY123_2', help_text='3連単 2番目', null=True)),
                ('pay123_3', models.IntegerField(blank=True, db_column='PAY123_3', help_text='3連単 3番目', null=True)),
                ('pay123_tie', models.IntegerField(blank=True, db_column='PAY123_TIE', help_text='3連単 同着', null=True)),
                ('pay123_12_1', models.IntegerField(blank=True, db_column='PAY123_12_1', null=True)),
                ('pay123_12_2', models.IntegerField(blank=True, db_column='PAY123_12_2', null=True)),
                ('pay123_12_3', models.IntegerField(blank=True, db_column='PAY123_12_3', null=True)),
                ('pay123_12_4_tie', models.IntegerField(blank=True, db_column='PAY123_12_4_TIE', null=True)),
                ('pay123_12_5_tie', models.IntegerField(blank=True, db_column='PAY123_12_5_TIE', null=True)),
                ('pay12_21', models.IntegerField(blank=True, db_column='PAY12_21', null=True)),
                ('pay12_21_tie', models.IntegerField(blank=True, db_column='PAY12_21_TIE', null=True)),
                ('pay12_12', models.IntegerField(blank=True, db_column='PAY12_12', null=True)),
                ('pay12_12_tie', models.IntegerField(blank=True, db_column='PAY12_12_TIE', null=True)),
                ('pay123_321', models.IntegerField(blank=True, db_column='PAY123_321', null=True)),
                ('pay123_321_tie', models.IntegerField(blank=True, db_column='PAY123_321_TIE', null=True)),
                ('pay123_123', models.IntegerField(blank=True, db_column='PAY123_123', null=True)),
                ('pay123_123_tie', models.IntegerField(blank=True, db_column='PAY123_123_TIE', null=True)),
            ],
            options={
                'verbose_name': '最終結果情報',
                'verbose_name_plural': '最終結果情報一覧',
                'db_table': 't_final_result_info',
            },
        ),
        migrations.DeleteModel(
            name='FinalHorseData',
        ),
        migrations.DeleteModel(
            name='FinalJockeyData',
        ),
    ]
