# Generated by Django 5.1.4 on 2025-04-10 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_folder', '0017_finalhorseinfo_finaljockeyinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finalresultinfo',
            name='corner_order',
            field=models.CharField(blank=True, db_column='CORNER_ORDER', help_text='コーナー順', max_length=20, null=True),
        ),
    ]
