# Generated by Django 5.1.4 on 2025-04-12 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_folder', '0018_alter_finalresultinfo_corner_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='finalresultinfo',
            name='horse_number',
            field=models.SmallIntegerField(db_column='HORSE_NUMBER', default=1, help_text='馬番号'),
            preserve_default=False,
        ),
    ]
