# Generated by Django 5.1.4 on 2025-04-12 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_folder', '0019_finalresultinfo_horse_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='basedata',
            name='count',
            field=models.CharField(db_comment='頭数', help_text='頭数', null=True),
        ),
        migrations.AlterField(
            model_name='basedata',
            name='race_place',
            field=models.CharField(db_comment='競技場', help_text='競技場', null=True),
        ),
    ]
