# Generated by Django 5.1.4 on 2025-04-27 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_folder', '0021_baseinfoview_horseinfoview_jockeyinfoview_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='finalbaseinfo',
            unique_together={('race_id', 'horse_id', 'jockey_id')},
        ),
    ]
