# Generated by Django 5.1.4 on 2025-04-27 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_folder', '0022_alter_finalbaseinfo_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='finalhorseinfo',
            unique_together={('today_race_date', 'history_race_date', 'horse_id', 'jockey')},
        ),
        migrations.AlterUniqueTogether(
            name='finaljockeyinfo',
            unique_together={('today_race_date', 'today_race_no', 'history_race_date', 'history_race_no', 'horse', 'jockey_id')},
        ),
        migrations.AlterUniqueTogether(
            name='finalresultinfo',
            unique_together={('race_id', 'horse_number')},
        ),
        migrations.AlterUniqueTogether(
            name='traininginfo',
            unique_together={('race_id', 'horse_id', 'jockey_id')},
        ),
    ]
