# Generated by Django 5.1.4 on 2025-04-27 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_folder', '0023_alter_finalhorseinfo_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='traininginfo',
            name='today_race_no',
            field=models.SmallIntegerField(db_column='RACE_NO_TODAY', help_text='当日レース番号'),
        ),
    ]
