# Generated by Django 5.1.4 on 2026-06-28 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_folder', '0029_urlmst_add_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='resultdata',
            name='last_3f',
            field=models.CharField(db_comment='上がり3ハロン', help_text='上がり3ハロン', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='resultdata',
            name='margin',
            field=models.CharField(db_comment='着差', help_text='着差', max_length=20, null=True),
        ),
    ]
